// OMNeT++ port of code/2_EDITED/pegasis_EDITED.cc (thesis ns-3 program).
// Generated by omnetpp/tools/port_ns3.py: the protocol logic below is the
// original code, unchanged; see the header of that script for what was adapted.

#include "WsnRuntime.h"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <random>
#include <string>
#include <vector>

using namespace std;

namespace wsn_pegasis_EDITED {
// ============================================================================
// PEGASIS -- EDITED (unified environment for fair cross-protocol comparison)
// ns-3.41 / C++
//
// SAME ALGORITHM as PEGASIS_ORIGINAL.cc (greedy chain from the node farthest
// from the BS, leader = node (i mod N), bidirectional fusion toward the
// leader, chain rebuilt when a node dies, per-node delivery counting) --
// only the ENVIRONMENT is standardized: 100x100 m field, BS at the centre
// (50,50), two-slope Efs/Emp/d0 radio, packet = 2000 bits.
// For the paper-faithful reproduction, see PEGASIS_ORIGINAL.cc.
// ============================================================================

struct ChainNode {
    uint32_t id = 0;
    double x = 0.0;
    double y = 0.0;
    double energy = 0.0;
    bool alive = true;
};

struct RoundResult {
    uint32_t round = 0;
    uint32_t alive = 0;
    uint32_t dead = 0;
    uint32_t chainLength = 0;
    uint32_t leader = numeric_limits<uint32_t>::max();
    uint32_t generated = 0;
    uint32_t delivered = 0;
    uint32_t lost = 0;
    uint64_t dataTx = 0;
    uint64_t dataRx = 0;
    double energyUsed = 0.0;
    double residualEnergy = 0.0;
    double avgDelayMs = 0.0;
    double pdr = 0.0;
    double throughputKbps = 0.0;
    double roundDurationSec = 0.0;
    bool chainRebuilt = false;
};

// ----------------------------- Network -------------------------------------
static constexpr uint32_t N = 100;
static constexpr double AREA = 100.0;   // ORIGINAL: paper's 50x50m field (Table 1)
static constexpr double BSX = 50.0;    // ORIGINAL: paper's stated BS position for this field
static double BS_Y = 50.0;   // switch (ini: defines = "BS_Y=...")
static double BSY = BS_Y;   // 50 = field centre; compile with -DBS_Y=-100 for the far-BS runs
static constexpr double E0 = 0.5;      // J/node

// --------------------------- Radio / traffic -------------------------------
// Optional security overhead (all 0 by default = the thesis results).
// Used for the "cost of hybrid cryptography" experiment (thesis proposal:
// symmetric inside the cluster, public-key only between the CH and the sink):
//   SEC_BITS        extra bits per frame (e.g. 104 = IEEE 802.15.4 security:
//                   5-byte auxiliary header + 8-byte MIC), data and control
//   SEC_NJ_PER_BIT  symmetric-cipher energy per bit, paid by the sender
//                   (encrypt) and by the receiver (decrypt)
//   SEC_SETUP_MJ    one-time public-key key-establishment energy per node at
//                   deployment, in mJ
//   SEC_AUTH_MJ     public-key energy paid by every newly elected CH (or chain
//                   leader) to authenticate to the sink and receive its
//                   credentials / session key, in mJ (hybrid scheme)
//   SEC_PK_TX_MJ    public-key operation per DATA packet, paid by the sender,
//   SEC_PK_RX_MJ    and by the receiving node, in mJ ("full public-key" mode:
//                   every packet encrypted with RSA/ECC; the sink is mains-powered)
static int SEC_BITS = 0;   // switch (ini: defines = "SEC_BITS=...")
static double SEC_NJ_PER_BIT = 0.0;   // switch (ini: defines = "SEC_NJ_PER_BIT=...")
static double SEC_SETUP_MJ = 0.0;   // switch (ini: defines = "SEC_SETUP_MJ=...")
static double SEC_AUTH_MJ = 0.0;   // switch (ini: defines = "SEC_AUTH_MJ=...")
static double SEC_PK_TX_MJ = 0.0;   // switch (ini: defines = "SEC_PK_TX_MJ=...")
static double SEC_PK_RX_MJ = 0.0;   // switch (ini: defines = "SEC_PK_RX_MJ=...")
//   SEC_PK_BS_MJ    public-key encryption (e.g. ECIES) of every data packet that
//                   goes straight to the sink, paid by the sender, in mJ
//                   ("asymmetric between CH and sink"; members still use AES)
static double SEC_PK_BS_MJ = 0.0;   // switch (ini: defines = "SEC_PK_BS_MJ=...")
//   SEC_KEYDIST     1 = at every cluster set-up the sink sends each node the new
//                   cluster key, wrapped with the node's own AES key (one extra
//                   control frame received per node; the sink pays its own TX)
static int SEC_KEYDIST = 0;   // switch (ini: defines = "SEC_KEYDIST=...")
// (PEGASIS has no clusters: chain neighbours keep the pairwise keys agreed at
//  deployment, so SEC_KEYDIST has no effect in this protocol.)
static double E_SEC = SEC_NJ_PER_BIT * 1e-9;   // J/bit
static double E_AUTH = SEC_AUTH_MJ * 1e-3;     // J per CH election
static double E_PK_TX = SEC_PK_TX_MJ * 1e-3;   // J per data packet sent
static double E_PK_RX = SEC_PK_RX_MJ * 1e-3;   // J per data packet received
static double E_PK_BS = SEC_PK_BS_MJ * 1e-3;   // J per data packet sent to the sink
static uint32_t PACKET_BITS = 2000 + SEC_BITS;
static constexpr double E_ELEC = 50e-9;   // J/bit
static constexpr double E_FS = 10e-12;        // J/bit/m^2 (UNIFIED two-slope)
static constexpr double E_MP = 0.0013e-12;    // J/bit/m^4
static double D0() { return std::sqrt(E_FS / E_MP); }
//  // J/bit/m^2 (ORIGINAL: single term, same as LEACH paper)
static constexpr double E_DA = 5e-9;      // J/bit (paper's fusion cost)
static constexpr double DATA_RATE = 250000.0;
static constexpr double LIGHT = 3.0e8;

static constexpr uint32_t MAX_ROUNDS = 20000; // run until the last node dies
static constexpr uint32_t SEED = 12345;

// ----------------------------- Geometry ------------------------------------
static double Dist(const ChainNode& a, const ChainNode& b) { return hypot(a.x - b.x, a.y - b.y); }
static double DistBS(const ChainNode& a) { return hypot(a.x - BSX, a.y - BSY); }

// ORIGINAL: single amplifier term (paper's Eq. 1, no d0 threshold)
static double TxEnergy(uint32_t bits, double d)
{
    const double pk = (bits >= PACKET_BITS) ? E_PK_TX : 0.0;   // full public-key mode only
    if (d <= 0.0) return pk + bits * (E_ELEC + E_SEC);
    if (d < D0()) return pk + bits * (E_ELEC + E_SEC + E_FS * d * d);
    return pk + bits * (E_ELEC + E_SEC + E_MP * pow(d, 4.0));
}
static double RxEnergy(uint32_t bits) { return ((bits >= PACKET_BITS) ? E_PK_RX : 0.0) + bits * (E_ELEC + E_SEC); }
static double AggEnergy(uint32_t bits) { return bits * E_DA; }
static double TxTimeSec(uint32_t bits) { return static_cast<double>(bits) / DATA_RATE; }
static double DelayMs(uint32_t bits, double d) { return (TxTimeSec(bits) + d / LIGHT) * 1000.0; }

// --------------------- Greedy chain construction ----------------------------
// Starts from the alive node FARTHEST from the BS (paper's stated rule:
// "we start with the furthest node from the BS ... to make sure that nodes
// farther from the BS have close neighbors").
static vector<uint32_t> BuildChain(const vector<ChainNode>& nodes)
{
    vector<uint32_t> alive;
    for (const auto& n : nodes) if (n.alive) alive.push_back(n.id);
    if (alive.empty()) return {};

    uint32_t start = alive.front();
    double bestD = -1.0;
    for (uint32_t id : alive) {
        double d = DistBS(nodes[id]);
        if (d > bestD) { bestD = d; start = id; }
    }

    vector<bool> used(nodes.size(), false);
    vector<uint32_t> chain;
    chain.push_back(start);
    used[start] = true;
    uint32_t current = start;

    for (size_t step = 1; step < alive.size(); ++step) {
        double bestDist = numeric_limits<double>::infinity();
        uint32_t bestId = numeric_limits<uint32_t>::max();
        for (uint32_t id : alive) {
            if (used[id]) continue;
            double d = Dist(nodes[current], nodes[id]);
            if (d < bestDist - 1e-12 || (fabs(d - bestDist) < 1e-12 && id < bestId)) {
                bestDist = d;
                bestId = id;
            }
        }
        if (bestId == numeric_limits<uint32_t>::max()) break;
        chain.push_back(bestId);
        used[bestId] = true;
        current = bestId;
    }
    return chain;
}

// ---------------------------- Round simulation -----------------------------
static RoundResult SimulateRound(vector<ChainNode>& nodes, vector<uint32_t>& chain,
                                 uint32_t round, uint32_t& leaderCounter)
{
    RoundResult r;
    r.round = round;

    const double before = [&]() { double s = 0.0; for (const auto& n : nodes) s += n.energy; return s; }();

    for (const auto& n : nodes) if (n.alive) ++r.generated;

    if (chain.size() <= 1) {
        if (chain.size() == 1) {
            uint32_t c = chain[0];
            if (nodes[c].alive) {
                const double d = DistBS(nodes[c]);
                const double tx = TxEnergy(PACKET_BITS, d);
                if (tx > nodes[c].energy) { nodes[c].energy = 0.0; nodes[c].alive = false; }
                else {
                    nodes[c].energy -= tx;
                    ++r.dataTx; ++r.dataRx;
                    r.delivered = 1;
                    r.avgDelayMs = DelayMs(PACKET_BITS, d);
                }
            }
        }
        r.chainLength = static_cast<uint32_t>(chain.size());
        r.lost = r.generated - r.delivered;
    } else {
        // PAPER: leader in round i is node number (i mod N); skip dead IDs.
        uint32_t leaderId = (round - 1) % N;
        while (!nodes[leaderId].alive)
            leaderId = (leaderId + 1) % N;
        uint32_t L = 0;
        for (uint32_t k = 0; k < chain.size(); ++k)
            if (chain[k] == leaderId) { L = k; break; }
        ++leaderCounter;
        r.leader = chain[L];
        // Hybrid security (0 by default): the leader of this round authenticates to the sink.
        if (E_AUTH > 0.0) nodes[r.leader].energy = max(0.0, nodes[r.leader].energy - E_AUTH);
        r.chainLength = static_cast<uint32_t>(chain.size());

        double delaySum = 0.0;
        bool anyLost = false;

        // One chain segment: data flows from chain[from] towards the leader.
        // "carried" = number of source readings fused into the message.
        auto runSegment = [&](int from, int step) -> uint32_t {
            uint32_t carried = 0;
            for (int j = from; j != static_cast<int>(L); j += step) {
                const uint32_t a = chain[j], b = chain[j + step];
                if (nodes[a].alive) ++carried;               // a's own reading
                if (!nodes[a].alive || !nodes[b].alive) { anyLost = true; carried = 0; continue; }
                const double d = Dist(nodes[a], nodes[b]);
                const double tx = TxEnergy(PACKET_BITS, d);
                const double rxAgg = RxEnergy(PACKET_BITS) + AggEnergy(PACKET_BITS);
                if (tx > nodes[a].energy) { nodes[a].energy = 0.0; nodes[a].alive = false; anyLost = true; carried = 0; continue; }
                nodes[a].energy -= tx;
                if (rxAgg > nodes[b].energy) { nodes[b].energy = 0.0; nodes[b].alive = false; anyLost = true; carried = 0; continue; }
                nodes[b].energy -= rxAgg;
                ++r.dataTx; ++r.dataRx;
                delaySum += DelayMs(PACKET_BITS, d);
            }
            return carried;   // readings that reached the leader from this side
        };
        uint32_t atLeader = 0;
        if (L > 0) atLeader += runSegment(0, +1);
        if (L + 1 < chain.size()) atLeader += runSegment(static_cast<int>(chain.size()) - 1, -1);

        // Leader -> BS (one fused message)
        uint32_t deliveredCount = 0;
        if (nodes[r.leader].alive) {
            ++atLeader;                                   // leader's own reading
            const double dBS = DistBS(nodes[r.leader]);
            const double tx = TxEnergy(PACKET_BITS, dBS) + E_PK_BS;
            if (tx > nodes[r.leader].energy) { nodes[r.leader].energy = 0.0; nodes[r.leader].alive = false; anyLost = true; }
            else {
                nodes[r.leader].energy -= tx;
                ++r.dataTx; ++r.dataRx;
                delaySum += DelayMs(PACKET_BITS, dBS);
                deliveredCount = atLeader;
            }
        } else {
            anyLost = true;
        }
        r.delivered = min(deliveredCount, r.generated);
        r.lost = r.generated - r.delivered;
        r.avgDelayMs = r.delivered ? delaySum : 0.0;
        r.chainRebuilt = anyLost;
    }

    double after = 0.0;
    r.alive = 0;
    for (auto& n : nodes) {
        if (n.energy <= 0.0) { n.energy = 0.0; n.alive = false; }
        after += n.energy;
        if (n.alive) ++r.alive;
    }
    r.dead = N - r.alive;
    r.energyUsed = max(0.0, before - after);
    r.residualEnergy = after;
    r.pdr = r.generated ? static_cast<double>(r.delivered) / r.generated : 0.0;

    const double dataTxTime = static_cast<double>(r.dataTx) * TxTimeSec(PACKET_BITS);
    r.roundDurationSec = dataTxTime;
    r.throughputKbps = r.roundDurationSec > 0.0
        ? static_cast<double>(r.delivered * PACKET_BITS) / r.roundDurationSec / 1000.0 : 0.0;

    return r;
}

static void InitSwitches(wsn::Hook& hook)
{
    BS_Y = static_cast<double>(hook.Define("BS_Y", 50.0));
    SEC_BITS = static_cast<int>(hook.Define("SEC_BITS", 0));
    SEC_NJ_PER_BIT = static_cast<double>(hook.Define("SEC_NJ_PER_BIT", 0.0));
    SEC_SETUP_MJ = static_cast<double>(hook.Define("SEC_SETUP_MJ", 0.0));
    SEC_AUTH_MJ = static_cast<double>(hook.Define("SEC_AUTH_MJ", 0.0));
    SEC_PK_TX_MJ = static_cast<double>(hook.Define("SEC_PK_TX_MJ", 0.0));
    SEC_PK_RX_MJ = static_cast<double>(hook.Define("SEC_PK_RX_MJ", 0.0));
    SEC_PK_BS_MJ = static_cast<double>(hook.Define("SEC_PK_BS_MJ", 0.0));
    SEC_KEYDIST = static_cast<int>(hook.Define("SEC_KEYDIST", 0));
    BSY = BS_Y;
    E_SEC = SEC_NJ_PER_BIT * 1e-9;
    E_AUTH = SEC_AUTH_MJ * 1e-3;
    E_PK_TX = SEC_PK_TX_MJ * 1e-3;
    E_PK_RX = SEC_PK_RX_MJ * 1e-3;
    E_PK_BS = SEC_PK_BS_MJ * 1e-3;
    PACKET_BITS = 2000 + SEC_BITS;
}

static int Run(wsn::Hook& HOOK)
{
    InitSwitches(HOOK);
    HOOK.SetBaseStation(BSX, BSY);

    wsn::Out() << "\n========================================\n";
    wsn::Out() << "  PEGASIS -- EDITED (unified environment)\n";
    wsn::Out() << "========================================\n";
    wsn::Out() << "Nodes = " << N << " | Area = " << AREA << "x" << AREA << " m | BS = (" << BSX << "," << BSY << ")\n";
    wsn::Out() << "Initial Energy = " << E0 << " J/node | Radio = two-slope Efs/Emp+d0 (unified model)\n";
    wsn::Out() << "========================================\n";

    mt19937 topologyRng(SEED);
    uniform_real_distribution<double> pos(0.0, AREA);
    vector<ChainNode> nodes(N);

    for (uint32_t i = 0; i < N; ++i) {
        nodes[i].id = i;
        nodes[i].x = pos(topologyRng);
        nodes[i].y = pos(topologyRng);
        nodes[i].energy = E0 - SEC_SETUP_MJ * 1e-3;   // key setup at deployment (0 by default)
        nodes[i].alive = true;
    }

    ofstream positions(wsn::CsvPath("node-positions.csv"));
    positions << "Node,X,Y\n";
    for (const auto& n : nodes) positions << n.id << ',' << n.x << ',' << n.y << '\n';
    positions << N << ',' << BSX << ',' << BSY << '\n';
    positions.close();

    ofstream rounds(wsn::CsvPath("pegasis_EDITED-results.csv"));
    ofstream energy(wsn::CsvPath("pegasis_EDITED-node-energy.csv"));
    ofstream lifetime(wsn::CsvPath("pegasis_EDITED-node-lifetime.csv"));
    if (!rounds || !energy || !lifetime) NS_FATAL_ERROR("Cannot create CSV output files.");

    rounds << "Round,Alive,Dead,ChainLength,Leader,Generated,Delivered,Lost,"
              "Data_TX,Data_RX,Energy_Used_J,Residual_Energy_J,Avg_Delay_ms,"
              "PDR,Round_Duration_s,Throughput_kbps,ChainRebuilt\n";
    energy << "Round,Node,Energy_J,Alive\n";
    lifetime << "Node,Death_Round\n";

    uint32_t FND = 0, HND = 0, LND = 0;
    bool fnd = false, hnd = false;
    vector<uint32_t> deathRound(N, 0);
    uint64_t totalGenerated = 0, totalDelivered = 0;
    double totalUsed = 0.0;
    uint32_t leaderCounter = 0;

    vector<uint32_t> chain = BuildChain(nodes);

    wsn::Out() << "\nSimulation starts...\n";

    for (uint32_t round = 1; round <= MAX_ROUNDS; ++round) {
        RoundResult r = SimulateRound(nodes, chain, round, leaderCounter);
        HOOK.Round(round, r, nodes);   // OMNeT++: one round = one step of simulation time

        if (r.chainRebuilt || chain.size() != nodes.size()) {
            // rebuild only if composition actually changed (a node died)
        }

        totalGenerated += r.generated;
        totalDelivered += r.delivered;
        totalUsed += r.energyUsed;

        rounds << fixed << setprecision(10)
               << r.round << ',' << r.alive << ',' << r.dead << ',' << r.chainLength << ','
               << (r.leader == numeric_limits<uint32_t>::max() ? -1 : static_cast<int>(r.leader)) << ','
               << r.generated << ',' << r.delivered << ',' << r.lost << ','
               << r.dataTx << ',' << r.dataRx << ',' << r.energyUsed << ',' << r.residualEnergy << ','
               << r.avgDelayMs << ',' << r.pdr << ',' << r.roundDurationSec << ',' << r.throughputKbps << ','
               << (r.chainRebuilt ? 1 : 0) << '\n';

        for (const auto& n : nodes) {
            energy << round << ',' << n.id << ',' << setprecision(10) << n.energy << ',' << (n.alive ? 1 : 0) << '\n';
            if (!n.alive && deathRound[n.id] == 0) deathRound[n.id] = round;
        }

        if (!fnd && r.dead >= 1) { FND = round; fnd = true; }
        if (!hnd && r.alive <= N / 2) { HND = round; hnd = true; }

        wsn::Out() << fixed << setprecision(4)
             << "Round " << setw(4) << round << " | Alive=" << setw(3) << r.alive
             << " | ChainLen=" << setw(3) << r.chainLength << " | PDR=" << setw(7) << r.pdr
             << " | Residual=" << setw(9) << r.residualEnergy << " J\n";

        if (r.alive == 0) { LND = round; break; }

        if (r.chainRebuilt) {
            chain = BuildChain(nodes);
            leaderCounter = 0;
        }
    }

    // LND is only reported when the last node really died (otherwise "Not reached").

    for (uint32_t i = 0; i < N; ++i)
        lifetime << i << ',' << (deathRound[i] ? to_string(deathRound[i]) : "Not_Dead") << '\n';

    rounds.close(); energy.close(); lifetime.close();

    const double overallPdr = totalGenerated ? static_cast<double>(totalDelivered) / totalGenerated : 0.0;

    wsn::Out() << "\n========================================\n";
    wsn::Out() << "             FINAL RESULTS\n";
    wsn::Out() << "========================================\n";
    wsn::Out() << "FND = " << (fnd ? to_string(FND) : "Not reached") << " rounds\n";
    wsn::Out() << "HND = " << (hnd ? to_string(HND) : "Not reached") << " rounds\n";
    wsn::Out() << "LND = " << (LND ? to_string(LND) : "Not reached") << " rounds\n";
    wsn::Out() << fixed << setprecision(6);
    wsn::Out() << "Total Energy Used = " << totalUsed << " J\n";
    wsn::Out() << "Overall PDR = " << overallPdr << "\n";
    wsn::Out() << "\nCSV outputs: pegasis_EDITED-results.csv, pegasis_EDITED-node-energy.csv,\n";
    wsn::Out() << "             pegasis_EDITED-node-lifetime.csv\n";
    wsn::Out() << "========================================\n";

    {   // OMNeT++: final metrics, exactly as computed above
        wsn::FinalView fv;
        fv.FND = fnd ? FND : 0; fv.HND = hnd ? HND : 0; fv.LND = LND;
        fv.pdr = overallPdr; fv.energyUsed = totalUsed;
        fv.generated = totalGenerated; fv.delivered = totalDelivered;
        HOOK.Finish(fv);
    }
    return 0;
}


} // namespace wsn_pegasis_EDITED

static wsn::Registrar wsn_pegasis_EDITED_registrar("pegasis_EDITED", "code/2_EDITED/pegasis_EDITED.cc", &wsn_pegasis_EDITED::Run, {"BS_Y", "SEC_BITS", "SEC_NJ_PER_BIT", "SEC_SETUP_MJ", "SEC_AUTH_MJ", "SEC_PK_TX_MJ", "SEC_PK_RX_MJ", "SEC_PK_BS_MJ", "SEC_KEYDIST"});
