// OMNeT++ port of code/2_EDITED/shleach_EDITED.cc (thesis ns-3 program).
// Generated by omnetpp/tools/port_ns3.py: the protocol logic below is the
// original code, unchanged; see the header of that script for what was adapted.

#include "WsnRuntime.h"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <random>
#include <string>
#include <vector>

using namespace std;

namespace wsn_shleach_EDITED {
// ============================================================================
// SH-LEACH (2015) -- EDITED (unified environment for fair cross-protocol comparison)
// ns-3.41 / C++
//
// SAME ALGORITHM as hybrid_SHLEACH_ORIGINAL.cc (paper Eq. 3 CH probability
// inside LEACH's round structure) -- only the ENVIRONMENT is standardized to
// match LEACH/HEED/PEGASIS/EECH-HEED: two-slope Efs/Emp/d0 radio model,
// packet = 2000 bits, BS at the field centre, N = 100, 100x100 m field.
// For the paper-faithful reproduction, see hybrid_SHLEACH_ORIGINAL.cc.
// ============================================================================

// ============================================================================
// HYBRID PROTOCOL (Literature Reproduction): SH-LEACH (Shrestha, Kim, Jung
// & Lee, 2015) -- "The Improved Energy Efficient LEACH Protocol Technology
// of Wireless Sensor Networks", Int'l J. Internet, Broadcasting and
// Communication, Vol.7 No.1.
// https://koreascience.kr/article/JAKO201532073077914.pdf
//
// This is the "Hybrid Protocol" stage of the thesis (Step 4): a direct
// reproduction of the ONLY published paper found (2015-2026 search) that
// combines LEACH and HEED specifically by name.
//
// DESIGN (per the paper, Sec. 3.3, Eq. 3):
//   - Keeps LEACH's round structure: setup (advertise, join, TDMA) +
//     steady-state data phase, every round. No G-set/epoch: "unlike
//     selecting each node in turns", every node draws a random number.
//   - CH probability (paper Eq. 3):
//
//        CHprob = Cprob * (Eresidual / Emax) * (Cprob * r)
//                 ---------------------------------------------
//                     1 + ( CHcho mod (1 / Cprob) )
//
//     r = current round; CHcho = number of nodes selected as CH so far
//     (whole network, up to the present round). A node becomes CH if
//     random(0,1) < CHprob (capped at 1).
//   - Everything else follows plain LEACH (as reproduced in leach_ORIGINAL):
//     CH advertisement heard by the whole field, nearest-CH join, TDMA
//     schedule to the farthest member, fusion of members + own signal, a
//     node with no CH transmits directly to the BS.
//   - NOT in the paper (documented gap-filling): if no node becomes CH in a
//     round (Eq. 3 gives ~0 in the first rounds), the highest-energy alive
//     node is made CH. The paper itself states that the method "does not
//     ensure the number of cluster heads".
//
// PARAMETERS: taken DIRECTLY from the paper's Table 1/2: N=100, 100x100m
// field, Cprob=0.10, Emax=0.5J, Eelec=50nJ/bit, one amplifier constant
// 100pJ/bit/m^2 (d^2 only). Packet size and sink location are NOT stated in
// the paper: packet = 2000 bits and sink at the field centre are documented
// assumptions. The paper plots 2000 rounds; the simulation here runs until
// the last node dies.
// ============================================================================

struct SensorNode {
    uint32_t id = 0;
    double x = 0.0;
    double y = 0.0;
    double energy = 0.0;
    bool alive = true;
    bool finalCH = false;
    uint32_t clusterHead = numeric_limits<uint32_t>::max();
    uint32_t chTimesServed = 0;  // CHcho: times already served as CH
};

struct RoundResult {
    uint32_t round = 0;
    uint32_t alive = 0;
    uint32_t dead = 0;
    uint32_t chCount = 0;
    uint32_t generated = 0;
    uint32_t delivered = 0;
    uint32_t lost = 0;
    uint32_t unclustered = 0;
    uint64_t controlTx = 0;
    uint64_t controlRx = 0;
    uint64_t dataTx = 0;
    uint64_t dataRx = 0;
    double energyUsed = 0.0;
    double residualEnergy = 0.0;
    double avgClusterSize = 0.0;
    double avgDelayMs = 0.0;
    double pdr = 0.0;
    double throughputKbps = 0.0;
    double roundDurationSec = 0.0;
};

// --------------------- Parameters taken DIRECTLY from the paper -------------
static constexpr uint32_t N = 100;
static constexpr double AREA = 100.0;
static constexpr double BSX = 50.0;   // NOT stated in paper -- assumed center
static double BS_Y = 50.0;   // switch (ini: defines = "BS_Y=...")
static double BSY = BS_Y;   // 50 = field centre; compile with -DBS_Y=-100 for the far-BS runs
static constexpr double EMAX = 0.5;   // J/node (paper's Emax)
static constexpr double CPROB = 0.10; // paper's Cprob
// UNIFIED ENVIRONMENT: radio model matches LEACH/HEED/EECH-HEED exactly
// (two-slope model with d0 threshold), NOT the paper's original single-slope
// Efs=100pJ model. This is a deliberate choice to enable a fair, apples-to-
// apples comparison across ALL protocols in this thesis, following the same
// practice as the EECH-HEED (2025) paper itself, which re-implements
// competitor protocols under its OWN unified test conditions rather than
// citing their original papers' numbers verbatim.
static constexpr double E_ELEC = 50e-9;   // J/bit (paper)
static constexpr double E_FS = 10e-12;     // J/bit/m^2 (UNIFIED two-slope)
static constexpr double E_MP = 0.0013e-12; // J/bit/m^4 (UNIFIED)
static constexpr uint32_t MAX_ROUNDS = 20000; // run until the last node dies (paper plots 2000 rounds)
static constexpr uint32_t SEED = 12345;

// --------------------- Assumptions NOT explicitly stated in the paper ------
static const double ADV_RANGE = AREA * std::sqrt(2.0); // m: CH advertisement heard by the whole field (as in LEACH)
static constexpr uint32_t PACKET_BITS = 2000;   // UNIFIED (was 4000 -- an assumption either way, paper doesn't state this)
static constexpr uint32_t CONTROL_BITS = 200;   // bits -- ASSUMPTION
static constexpr double E_DA = 5e-9;            // J/bit aggregation -- ASSUMPTION (standard value)
static constexpr double DATA_RATE = 250000.0;   // bit/s -- ASSUMPTION
static constexpr double LIGHT = 3.0e8;          // m/s

// ----------------------------- Geometry ------------------------------------
static double Dist(const SensorNode& a, const SensorNode& b) { return hypot(a.x - b.x, a.y - b.y); }
static double DistBS(const SensorNode& a) { return hypot(a.x - BSX, a.y - BSY); }

// UNIFIED: two-slope radio model
static double D0() { return sqrt(E_FS / E_MP); }
static double TxEnergy(uint32_t bits, double d)
{
    if (d < D0()) return bits * (E_ELEC + E_FS * d * d);
    return bits * (E_ELEC + E_MP * pow(d, 4.0));
}
static double RxEnergy(uint32_t bits) { return bits * E_ELEC; }
static double AggEnergy(uint32_t bits) { return bits * E_DA; }
static double TxTimeSec(uint32_t bits) { return static_cast<double>(bits) / DATA_RATE; }
static double DelayMs(uint32_t bits, double d) { return (TxTimeSec(bits) + d / LIGHT) * 1000.0; }

// ------------------------ SH-LEACH CH selection -----------------------------
// Paper Eq. 3. CHcho = number of CH selections in the network so far.
static uint64_t g_chCho = 0;

static uint32_t RunSHLEACH(vector<SensorNode>& nodes, uint32_t round, mt19937& rng)
{
    uniform_real_distribution<double> U(0.0, 1.0);

    for (auto& n : nodes) { n.finalCH = false; n.clusterHead = numeric_limits<uint32_t>::max(); }

    const uint64_t period = static_cast<uint64_t>(llround(1.0 / CPROB));   // 1/Cprob
    const double denom = 1.0 + static_cast<double>(g_chCho % period);
    vector<uint32_t> candidates;
    for (auto& n : nodes) {
        if (!n.alive) continue;
        const double prob = min(1.0, CPROB * (n.energy / EMAX) * (CPROB * static_cast<double>(round)) / denom);
        if (U(rng) < prob) candidates.push_back(n.id);
    }

    if (candidates.empty()) {
        // NOT in the paper (see header): force the highest-energy alive node
        double bestE = -1.0;
        int best = -1;
        for (const auto& n : nodes) {
            if (n.alive && n.energy > bestE) { bestE = n.energy; best = static_cast<int>(n.id); }
        }
        if (best >= 0) candidates.push_back(static_cast<uint32_t>(best));
    }

    for (uint32_t id : candidates) {
        nodes[id].finalCH = true;
        nodes[id].chTimesServed++;
    }
    g_chCho += candidates.size();

    uint32_t chCount = static_cast<uint32_t>(candidates.size());

    // ---- Cluster formation: nearest-distance join ----
    for (auto& n : nodes) {
        n.clusterHead = numeric_limits<uint32_t>::max();
        if (!n.alive) continue;
        if (n.finalCH) { n.clusterHead = n.id; continue; }

        double bestDistance = numeric_limits<double>::infinity();
        uint32_t bestCH = numeric_limits<uint32_t>::max();
        for (const auto& c : nodes) {
            if (!c.alive || !c.finalCH) continue;
            const double d = Dist(n, c);
            if (d < bestDistance - 1e-12 || (fabs(d - bestDistance) < 1e-12 && c.id < bestCH)) {
                bestDistance = d;
                bestCH = c.id;
            }
        }
        if (bestCH != numeric_limits<uint32_t>::max()) n.clusterHead = bestCH;
    }

    return chCount;
}

// ---------------------------- Round simulation -----------------------------
static RoundResult SimulateRound(vector<SensorNode>& nodes, uint32_t round)
{
    RoundResult r;
    r.round = round;

    const double before = [&]() { double s = 0.0; for (const auto& n : nodes) s += n.energy; return s; }();

    // ---- Setup phases: same LEACH-style overhead structure (advertise, join, TDMA) ----
    for (uint32_t c = 0; c < N; ++c) {
        if (!nodes[c].alive || !nodes[c].finalCH) continue;
        const double tx = TxEnergy(CONTROL_BITS, ADV_RANGE);
        if (tx > nodes[c].energy) { nodes[c].energy = 0.0; nodes[c].alive = false; nodes[c].finalCH = false; continue; }
        nodes[c].energy -= tx;
        ++r.controlTx;
        for (uint32_t v = 0; v < N; ++v) {
            if (v == c || !nodes[v].alive) continue;
            const double rx = RxEnergy(CONTROL_BITS);
            if (rx > nodes[v].energy) { nodes[v].energy = 0.0; nodes[v].alive = false; nodes[v].finalCH = false; continue; }
            nodes[v].energy -= rx;
            ++r.controlRx;
        }
    }

    for (auto& n : nodes) if (!n.alive) n.finalCH = false;

    for (auto& n : nodes) {
        n.clusterHead = numeric_limits<uint32_t>::max();
        if (!n.alive) continue;
        if (n.finalCH) { n.clusterHead = n.id; continue; }
        double bestDistance = numeric_limits<double>::infinity();
        uint32_t bestCH = numeric_limits<uint32_t>::max();
        for (const auto& c : nodes) {
            if (!c.alive || !c.finalCH) continue;
            const double d = Dist(n, c);
            if (d < bestDistance - 1e-12 || (fabs(d - bestDistance) < 1e-12 && c.id < bestCH)) {
                bestDistance = d;
                bestCH = c.id;
            }
        }
        n.clusterHead = bestCH;
    }

    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive || nodes[i].finalCH) continue;
        const uint32_t c = nodes[i].clusterHead;
        if (c >= N || !nodes[c].alive || !nodes[c].finalCH) continue;
        const double d = Dist(nodes[i], nodes[c]);
        const double tx = TxEnergy(CONTROL_BITS, d);
        const double rx = RxEnergy(CONTROL_BITS);
        if (tx > nodes[i].energy || rx > nodes[c].energy) {
            if (tx > nodes[i].energy) { nodes[i].energy = 0.0; nodes[i].alive = false; nodes[i].finalCH = false; }
            if (rx > nodes[c].energy) { nodes[c].energy = 0.0; nodes[c].alive = false; nodes[c].finalCH = false; }
            continue;
        }
        nodes[i].energy -= tx;
        nodes[c].energy -= rx;
        ++r.controlTx;
        ++r.controlRx;
    }

    for (uint32_t c = 0; c < N; ++c) {
        if (!nodes[c].alive || !nodes[c].finalCH) continue;
        bool hasMember = false;
        double farthest = 0.0;
        for (uint32_t i = 0; i < N; ++i)
            if (nodes[i].alive && !nodes[i].finalCH && nodes[i].clusterHead == c) { hasMember = true; farthest = max(farthest, Dist(nodes[i], nodes[c])); }
        if (!hasMember) continue;
        const double tx = TxEnergy(CONTROL_BITS, farthest);   // TDMA schedule to the farthest member
        if (tx > nodes[c].energy) { nodes[c].energy = 0.0; nodes[c].alive = false; nodes[c].finalCH = false; continue; }
        nodes[c].energy -= tx;
        ++r.controlTx;
        for (uint32_t i = 0; i < N; ++i) {
            if (!nodes[i].alive || nodes[i].finalCH || nodes[i].clusterHead != c) continue;
            const double rx = RxEnergy(CONTROL_BITS);
            if (rx > nodes[i].energy) { nodes[i].energy = 0.0; nodes[i].alive = false; nodes[i].finalCH = false; continue; }
            nodes[i].energy -= rx;
            ++r.controlRx;
        }
    }

    r.alive = 0; r.chCount = 0;
    for (auto& n : nodes) {
        if (n.energy <= 0.0) { n.energy = 0.0; n.alive = false; n.finalCH = false; }
        if (n.alive) { ++r.alive; if (n.finalCH) ++r.chCount; }
    }

    for (auto& n : nodes) {
        if (!n.alive) { n.clusterHead = numeric_limits<uint32_t>::max(); continue; }
        if (n.finalCH) { n.clusterHead = n.id; continue; }
        double bestDistance = numeric_limits<double>::infinity();
        uint32_t bestCH = numeric_limits<uint32_t>::max();
        for (const auto& c : nodes) {
            if (!c.alive || !c.finalCH) continue;
            const double d = Dist(n, c);
            if (d < bestDistance - 1e-12 || (fabs(d - bestDistance) < 1e-12 && c.id < bestCH)) {
                bestDistance = d;
                bestCH = c.id;
            }
        }
        n.clusterHead = bestCH;
    }

    for (const auto& n : nodes) if (n.alive) ++r.generated;

    vector<uint32_t> membersPerCH(N, 0);
    vector<bool> memberDelivered(N, false);
    vector<double> delayToCH(N, 0.0);
    uint32_t directDelivered = 0;
    double directDelaySum = 0.0;

    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive || nodes[i].finalCH) continue;
        const uint32_t c = nodes[i].clusterHead;
        if (c >= N || !nodes[c].alive || !nodes[c].finalCH) {
            // no CH: transmit directly to the BS (as in LEACH)
            ++r.unclustered;
            const double dBS = DistBS(nodes[i]);
            const double txBS = TxEnergy(PACKET_BITS, dBS);
            if (txBS > nodes[i].energy) { nodes[i].energy = 0.0; nodes[i].alive = false; continue; }
            nodes[i].energy -= txBS;
            ++r.dataTx; ++r.dataRx; ++directDelivered;
            directDelaySum += DelayMs(PACKET_BITS, dBS);
            continue;
        }
        const double d = Dist(nodes[i], nodes[c]);
        const double tx = TxEnergy(PACKET_BITS, d);
        const double rx = RxEnergy(PACKET_BITS);
        if (tx > nodes[i].energy || rx > nodes[c].energy) { ++r.lost; continue; }
        nodes[i].energy -= tx;
        nodes[c].energy -= rx;
        ++r.dataTx; ++r.dataRx;
        ++membersPerCH[c];
        memberDelivered[i] = true;
        delayToCH[i] = DelayMs(PACKET_BITS, d);
    }

    double delaySum = 0.0;
    uint32_t deliveredSources = 0;

    for (uint32_t c = 0; c < N; ++c) {
        if (!nodes[c].alive || !nodes[c].finalCH) continue;
        const uint32_t members = membersPerCH[c];
        const double agg = static_cast<double>(members + 1) * AggEnergy(PACKET_BITS); // members' + own signal
        if (agg > nodes[c].energy) { nodes[c].energy = 0.0; nodes[c].alive = false; nodes[c].finalCH = false; ++r.lost; continue; }
        nodes[c].energy -= agg;
        const double dBS = DistBS(nodes[c]);
        const double txBS = TxEnergy(PACKET_BITS, dBS);
        if (txBS > nodes[c].energy) { nodes[c].energy = 0.0; nodes[c].alive = false; nodes[c].finalCH = false; ++r.lost; continue; }
        nodes[c].energy -= txBS;
        ++r.dataTx; ++r.dataRx;
        deliveredSources += members + 1;
        delaySum += DelayMs(PACKET_BITS, dBS);
        for (uint32_t i = 0; i < N; ++i)
            if (memberDelivered[i] && nodes[i].clusterHead == c)
                delaySum += delayToCH[i] + DelayMs(PACKET_BITS, dBS);
    }

    deliveredSources += directDelivered;
    delaySum += directDelaySum;
    r.delivered = min(deliveredSources, r.generated);
    r.lost = r.generated - r.delivered;

    double after = 0.0;
    uint32_t assigned = 0;
    r.alive = 0;
    for (auto& n : nodes) {
        if (n.energy <= 0.0) { n.energy = 0.0; n.alive = false; n.finalCH = false; }
        after += n.energy;
        if (n.alive) ++r.alive;
        if (n.alive && !n.finalCH && n.clusterHead < N && nodes[n.clusterHead].alive && nodes[n.clusterHead].finalCH)
            ++assigned;
    }

    r.dead = N - r.alive;
    r.energyUsed = max(0.0, before - after);
    r.residualEnergy = after;
    r.avgClusterSize = r.chCount ? static_cast<double>(assigned + r.chCount) / r.chCount : 0.0;

    if (r.alive == 0) {
        r.chCount = 0; r.generated = 0; r.delivered = 0; r.lost = 0; r.unclustered = 0;
        r.avgClusterSize = 0.0; r.avgDelayMs = 0.0; r.pdr = 0.0; r.throughputKbps = 0.0;
    }

    r.pdr = r.generated ? static_cast<double>(r.delivered) / r.generated : 0.0;
    r.avgDelayMs = r.delivered ? delaySum / r.delivered : 0.0;

    const double controlTime = static_cast<double>(r.controlTx) * TxTimeSec(CONTROL_BITS);
    const double dataTxTime = static_cast<double>(r.dataTx) * TxTimeSec(PACKET_BITS);
    r.roundDurationSec = controlTime + dataTxTime;
    r.throughputKbps = r.roundDurationSec > 0.0
        ? static_cast<double>(r.delivered * PACKET_BITS) / r.roundDurationSec / 1000.0 : 0.0;

    return r;
}

static void InitSwitches(wsn::Hook& hook)
{
    BS_Y = static_cast<double>(hook.Define("BS_Y", 50.0));
    BSY = BS_Y;
}

static int Run(wsn::Hook& HOOK)
{
    InitSwitches(HOOK);
    HOOK.SetBaseStation(BSX, BSY);

    wsn::Out() << "\n========================================\n";
    wsn::Out() << "  HYBRID PROTOCOL (Literature): SH-LEACH (Shrestha et al., 2015)\n";
    wsn::Out() << "========================================\n";
    wsn::Out() << "Nodes = " << N << " | Area = " << AREA << "x" << AREA << " m\n";
    wsn::Out() << "Cprob = " << CPROB << " | Emax = " << EMAX << " J | Radio: two-slope (unified)\n";
    wsn::Out() << "CH probability = paper Eq. 3: Cprob*(E/Emax)*(Cprob*r)/(1 + CHcho mod 1/Cprob)\n";
    wsn::Out() << "NOTE: packet size (" << PACKET_BITS << " bits) and sink location (center) are\n";
    wsn::Out() << "      ASSUMPTIONS -- not explicitly stated in the paper.\n";
    wsn::Out() << "========================================\n";

    mt19937 topologyRng(SEED);
    mt19937 electionRng(SEED + 1);
    uniform_real_distribution<double> pos(0.0, AREA);
    vector<SensorNode> nodes(N);

    for (uint32_t i = 0; i < N; ++i) {
        nodes[i].id = i;
        nodes[i].x = pos(topologyRng);
        nodes[i].y = pos(topologyRng);
        nodes[i].energy = EMAX;
        nodes[i].alive = true;
    }

    ofstream positions(wsn::CsvPath("node-positions.csv"));
    positions << "Node,X,Y\n";
    for (const auto& n : nodes) positions << n.id << ',' << n.x << ',' << n.y << '\n';
    positions << N << ',' << BSX << ',' << BSY << '\n';
    positions.close();

    ofstream rounds(wsn::CsvPath("shleach_EDITED-results.csv"));
    ofstream energy(wsn::CsvPath("shleach_EDITED-node-energy.csv"));
    ofstream lifetime(wsn::CsvPath("shleach_EDITED-node-lifetime.csv"));
    if (!rounds || !energy || !lifetime) NS_FATAL_ERROR("Cannot create CSV output files.");

    rounds << "Round,Alive,Dead,CH_Count,Generated,Delivered,Lost,Unclustered,"
              "Control_TX,Control_RX,Data_TX,Data_RX,"
              "Energy_Used_J,Residual_Energy_J,Avg_Cluster_Size,Avg_Delay_ms,"
              "PDR,Round_Duration_s,Throughput_kbps\n";
    energy << "Round,Node,Energy_J,Alive,Is_CH,ClusterHead\n";
    lifetime << "Node,Death_Round\n";

    uint32_t FND = 0, HND = 0, LND = 0;
    bool fnd = false, hnd = false;
    vector<uint32_t> deathRound(N, 0);
    uint64_t totalGenerated = 0, totalDelivered = 0;
    double totalUsed = 0.0;

    wsn::Out() << "\nSimulation starts...\n";

    for (uint32_t round = 1; round <= MAX_ROUNDS; ++round) {
        RunSHLEACH(nodes, round, electionRng);
        RoundResult r = SimulateRound(nodes, round);
        HOOK.Round(round, r, nodes);   // OMNeT++: one round = one step of simulation time

        totalGenerated += r.generated;
        totalDelivered += r.delivered;
        totalUsed += r.energyUsed;

        rounds << fixed << setprecision(10)
               << r.round << ',' << r.alive << ',' << r.dead << ',' << r.chCount << ','
               << r.generated << ',' << r.delivered << ',' << r.lost << ',' << r.unclustered << ','
               << r.controlTx << ',' << r.controlRx << ','
               << r.dataTx << ',' << r.dataRx << ',' << r.energyUsed << ',' << r.residualEnergy << ','
               << r.avgClusterSize << ',' << r.avgDelayMs << ',' << r.pdr << ','
               << r.roundDurationSec << ',' << r.throughputKbps << '\n';

        for (const auto& n : nodes) {
            energy << round << ',' << n.id << ',' << setprecision(10) << n.energy << ','
                   << (n.alive ? 1 : 0) << ',' << (n.alive && n.finalCH ? 1 : 0) << ','
                   << (n.clusterHead < N ? to_string(n.clusterHead) : "-1") << '\n';
            if (!n.alive && deathRound[n.id] == 0) deathRound[n.id] = round;
        }

        if (!fnd && r.dead >= 1) { FND = round; fnd = true; }
        if (!hnd && r.alive <= N / 2) { HND = round; hnd = true; }

        wsn::Out() << fixed << setprecision(4)
             << "Round " << setw(4) << round << " | Alive=" << setw(3) << r.alive
             << " | CH=" << setw(3) << r.chCount << " | PDR=" << setw(7) << r.pdr
             << " | Residual=" << setw(9) << r.residualEnergy << " J\n";

        if (r.alive == 0) { LND = round; break; }
    }

    // LND is only reported when the last node really died.

    for (uint32_t i = 0; i < N; ++i)
        lifetime << i << ',' << (deathRound[i] ? to_string(deathRound[i]) : "Not_Dead") << '\n';

    rounds.close(); energy.close(); lifetime.close();

    const double overallPdr = totalGenerated ? static_cast<double>(totalDelivered) / totalGenerated : 0.0;

    wsn::Out() << "\n========================================\n";
    wsn::Out() << "             FINAL RESULTS\n";
    wsn::Out() << "========================================\n";
    wsn::Out() << "FND = " << (fnd ? to_string(FND) : "Not reached") << " rounds\n";
    wsn::Out() << "HND = " << (hnd ? to_string(HND) : "Not reached") << " rounds\n";
    wsn::Out() << "LND = " << (LND ? to_string(LND) : "Not reached") << " rounds\n";
    wsn::Out() << fixed << setprecision(6);
    wsn::Out() << "Total Energy Used = " << totalUsed << " J\n";
    wsn::Out() << "Overall PDR = " << overallPdr << "\n";
    wsn::Out() << "\nCSV outputs: shleach_EDITED-results.csv, shleach_EDITED-node-energy.csv,\n";
    wsn::Out() << "             shleach_EDITED-node-lifetime.csv\n";
    wsn::Out() << "========================================\n";

    {   // OMNeT++: final metrics, exactly as computed above
        wsn::FinalView fv;
        fv.FND = fnd ? FND : 0; fv.HND = hnd ? HND : 0; fv.LND = LND;
        fv.pdr = overallPdr; fv.energyUsed = totalUsed;
        fv.generated = totalGenerated; fv.delivered = totalDelivered;
        HOOK.Finish(fv);
    }
    return 0;
}


} // namespace wsn_shleach_EDITED

static wsn::Registrar wsn_shleach_EDITED_registrar("shleach_EDITED", "code/2_EDITED/shleach_EDITED.cc", &wsn_shleach_EDITED::Run, {"BS_Y"});
