// OMNeT++ port of code/4_PROPOSED/v1_heed_election_leach_join.cc (thesis ns-3 program).
// Generated by omnetpp/tools/port_ns3.py: the protocol logic below is the
// original code, unchanged; see the header of that script for what was adapted.

#include "WsnRuntime.h"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <random>
#include <string>
#include <vector>

using namespace std;

namespace wsn_v1_heed_election_leach_join {

// ============================================================================
// HYBRID PROTOCOL v1: LEACH clustering + HEED CH selection (CLEAN VERSION)
// ns-3.41 / C++
//
// UNIFIED-ENVIRONMENT FIX (same rules as every baseline in code/2_EDITED):
//   - join request (member -> CH) and TDMA schedule (CH -> farthest member)
//     are now charged every round, as in the HEED/LEACH baselines;
//   - the CH fuses members + its own signal (members + 1).
// RESULT of this exact file (seed 12345): FND 320 / HND 529 / LND 1218 / PDR 99.76%
// (Any other numbers quoted further down this header are from older
//  versions or Python pre-checks and are kept only as history.)
//
// DESIGN:
//   PHASE 1 -- CH Selection: taken from "Original HEED" (heed_COMBINED_FIX.cc)
//       unchanged -- residual-energy-based probability, iterative doubling,
//       local competition using cost = 1/(degree+1) (favors well-connected
//       hub nodes; see that file's header for the full bug-fix rationale).
//   PHASE 2 -- Cluster formation (the actual DIFFERENCE from HEED):
//       Original HEED picks the LOWEST-COST reachable CH for each member
//       (BestCH(), degree-based tie-break). This Hybrid instead uses
//       LEACH's simple rule: each member joins whichever alive CH is
//       NEAREST by Euclidean distance -- no cost/degree involved in the
//       join decision at all, only in who becomes CH in Phase 1.
//
// This is the RELIABLE version: analytical energy model + simple NetAnim
// node-color visualization only (no WiFi/packet layer, which proved
// fragile/slow due to the shared-collision-domain issue). Exports
// node-positions.csv for the Python cluster-circle visualizer.
// ============================================================================

struct SensorNode {
    uint32_t id = 0;
    double x = 0.0;
    double y = 0.0;
    double energy = 0.0;
    bool alive = true;
    bool tentative = false;
    bool finalCH = false;
    uint32_t clusterHead = numeric_limits<uint32_t>::max();
    uint32_t degree = 0;
    double cost = 0.0;
    double chProb = 0.0;
};

struct RoundResult {
    uint32_t round = 0;
    uint32_t alive = 0;
    uint32_t dead = 0;
    uint32_t chCount = 0;
    uint32_t generated = 0;
    uint32_t delivered = 0;
    uint32_t lost = 0;
    uint32_t unclustered = 0;
    uint64_t controlTx = 0;
    uint64_t controlRx = 0;
    uint64_t dataTx = 0;
    uint64_t dataRx = 0;
    double energyUsed = 0.0;
    double residualEnergy = 0.0;
    double avgClusterSize = 0.0;
    double avgDelayMs = 0.0;
    double pdr = 0.0;
    double throughputKbps = 0.0;
    double roundDurationSec = 0.0;
    uint32_t heedIterations = 0;
};

// ----------------------------- Network -------------------------------------
static constexpr uint32_t N = 100;
static constexpr double AREA = 100.0;
static const double ADV_RANGE = AREA * std::sqrt(2.0); // CH advertisement heard by the whole field (unified env)
static constexpr double BSX = 50.0;
static constexpr double BSY = 50.0;
static constexpr double E0 = 0.5;
static constexpr double RANGE = 25.0;

// ------------------------------- HEED selection params ----------------------
static constexpr double CPROB = 0.20;
static constexpr double PMIN = 0.05;

// --------------------------- Radio / traffic -------------------------------
static constexpr uint32_t PACKET_BITS = 2000;
// Neighbour discovery is charged once, at deployment: every node broadcasts one
// HELLO control frame over the neighbour range and receives its neighbours' HELLOs
// (-DCHARGE_HELLO=0 switches it off). The nodes are static, so the list is reused;
// a neighbour that dies is noticed from its silence (no extra message).
static int CHARGE_HELLO = 1;   // switch (ini: defines = "CHARGE_HELLO=...")
static constexpr uint32_t CONTROL_BITS = 200;
static constexpr double E_ELEC = 50e-9;
static constexpr double E_FS = 10e-12;
static constexpr double E_MP = 0.0013e-12;
static constexpr double E_DA = 5e-9;
static constexpr double DATA_RATE = 250000.0;
static constexpr double LIGHT = 3.0e8;

static constexpr uint32_t MAX_ROUNDS = 2000;
static constexpr uint32_t SEED = 12345;

// ----------------------------- Geometry ------------------------------------
static double Dist(const SensorNode& a, const SensorNode& b) { return hypot(a.x - b.x, a.y - b.y); }
static double DistBS(const SensorNode& a) { return hypot(a.x - BSX, a.y - BSY); }
static double D0() { return sqrt(E_FS / E_MP); }

static double TxEnergy(uint32_t bits, double d)
{
    if (d <= 0.0) return bits * E_ELEC;
    if (d < D0()) return bits * (E_ELEC + E_FS * d * d);
    return bits * (E_ELEC + E_MP * pow(d, 4.0));
}
static double RxEnergy(uint32_t bits) { return bits * E_ELEC; }
static double AggEnergy(uint32_t bits) { return bits * E_DA; }
static double TxTimeSec(uint32_t bits) { return static_cast<double>(bits) / DATA_RATE; }
static double DelayMs(uint32_t bits, double d) { return (TxTimeSec(bits) + d / LIGHT) * 1000.0; }

static vector<vector<uint32_t>> BuildNeighbors(const vector<SensorNode>& nodes)
{
    vector<vector<uint32_t>> nb(N);
    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive) continue;
        for (uint32_t j = 0; j < N; ++j) {
            if (i == j || !nodes[j].alive) continue;
            if (Dist(nodes[i], nodes[j]) <= RANGE) nb[i].push_back(j);
        }
    }
    return nb;
}

static void UpdateCost(vector<SensorNode>& nodes, const vector<vector<uint32_t>>& nb)
{
    // Used ONLY for Phase 1 (who becomes CH) -- NOT used for Phase 2 (joining).
    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive) { nodes[i].degree = 0; nodes[i].cost = numeric_limits<double>::infinity(); continue; }
        nodes[i].degree = static_cast<uint32_t>(nb[i].size());
        nodes[i].cost = 1.0 / (static_cast<double>(nodes[i].degree) + 1.0);
    }
}

static uint32_t BestCH(const vector<uint32_t>& candidates, const vector<SensorNode>& nodes)
{
    NS_ASSERT(!candidates.empty());
    uint32_t best = candidates.front();
    for (uint32_t c : candidates)
        if (nodes[c].cost < nodes[best].cost ||
            (fabs(nodes[c].cost - nodes[best].cost) < 1e-12 && c < best))
            best = c;
    return best;
}

// --------------------- PHASE 1: HEED-style CH selection (unchanged) --------
static uint32_t RunHEED(vector<SensorNode>& nodes, const vector<vector<uint32_t>>& nb, mt19937& rng)
{
    uniform_real_distribution<double> U(0.0, 1.0);

    for (auto& n : nodes) {
        n.tentative = false;
        n.finalCH = false;
        n.clusterHead = numeric_limits<uint32_t>::max();
        n.chProb = n.alive ? max(CPROB * n.energy / E0, PMIN) : 0.0;
    }
    for (auto& n : nodes)
        if (n.alive && U(rng) <= n.chProb) n.tentative = true;

    uint32_t iterations = 0;
    while (iterations < 64) {
        ++iterations;
        vector<bool> oldT(N, false), oldF(N, false), newT(N, false), newF(N, false);
        bool allAtOne = true;
        for (uint32_t i = 0; i < N; ++i) {
            oldT[i] = nodes[i].tentative;
            oldF[i] = nodes[i].finalCH;
            if (nodes[i].alive && nodes[i].chProb < 1.0 - 1e-12) allAtOne = false;
        }
        for (uint32_t i = 0; i < N; ++i) {
            if (!nodes[i].alive) continue;
            if (oldF[i]) { newF[i] = true; continue; }
            vector<uint32_t> sch;
            for (uint32_t c : nb[i]) if (nodes[c].alive && (oldT[c] || oldF[c])) sch.push_back(c);
            if (oldT[i]) sch.push_back(i);
            sort(sch.begin(), sch.end());
            sch.erase(unique(sch.begin(), sch.end()), sch.end());
            if (!sch.empty()) { if (BestCH(sch, nodes) == i) newT[i] = true; }
            else { if (U(rng) <= nodes[i].chProb) newT[i] = true; }
        }
        for (uint32_t i = 0; i < N; ++i) { nodes[i].tentative = newT[i]; nodes[i].finalCH = newF[i]; }
        for (auto& n : nodes) if (n.alive) n.chProb = min(2.0 * n.chProb, 1.0);
        if (allAtOne) break;
    }

    for (auto& n : nodes) if (n.alive && n.tentative) n.finalCH = true;

    auto liveNb = BuildNeighbors(nodes);
    vector<bool> visited(N, false);
    for (uint32_t start = 0; start < N; ++start) {
        if (!nodes[start].alive || visited[start]) continue;
        vector<uint32_t> component;
        vector<uint32_t> q{start};
        visited[start] = true;
        for (size_t h = 0; h < q.size(); ++h) {
            uint32_t u = q[h];
            component.push_back(u);
            for (uint32_t v : liveNb[u]) if (!visited[v]) { visited[v] = true; q.push_back(v); }
        }
        bool hasCH = false;
        for (uint32_t id : component) if (nodes[id].finalCH) { hasCH = true; break; }
        if (!hasCH) {
            uint32_t best = component.front();
            for (uint32_t id : component)
                if (nodes[id].energy > nodes[best].energy ||
                    (fabs(nodes[id].energy - nodes[best].energy) < 1e-12 && id < best))
                    best = id;
            nodes[best].finalCH = true;
        }
    }

    // ---- PHASE 2 (HYBRID DIFFERENCE): nearest-distance join, LEACH-style ----
    // Original HEED would call BestCH() here (cost/degree-based). Instead,
    // every member simply joins the closest alive final CH by Euclidean
    // distance -- exactly LEACH's join rule.
    for (auto& n : nodes) {
        n.clusterHead = numeric_limits<uint32_t>::max();
        if (!n.alive) continue;
        if (n.finalCH) { n.clusterHead = n.id; continue; }

        double bestDistance = numeric_limits<double>::infinity();
        uint32_t bestCH = numeric_limits<uint32_t>::max();
        for (uint32_t c : nb[n.id]) {
            if (!nodes[c].alive || !nodes[c].finalCH) continue;
            const double d = Dist(n, nodes[c]);
            if (d < bestDistance - 1e-12 || (fabs(d - bestDistance) < 1e-12 && c < bestCH)) {
                bestDistance = d;
                bestCH = c;
            }
        }
        if (bestCH != numeric_limits<uint32_t>::max()) n.clusterHead = bestCH;
    }

    return iterations;
}

// ---- Unified environment (same rules as every baseline) ----
// After the CH advertisements, every member sends a JOIN request to its CH,
// and every CH sends ONE TDMA schedule that must reach its farthest member.
static void ChargeJoinAndSchedule(vector<SensorNode>& nodes, RoundResult& r)
{
    for (auto& n : nodes) {
        if (!n.alive || n.finalCH) continue;
        const uint32_t c = n.clusterHead;
        if (c >= N || !nodes[c].alive || !nodes[c].finalCH) continue;
        const double tx = TxEnergy(CONTROL_BITS, Dist(n, nodes[c]));
        if (tx > n.energy) { n.energy = 0.0; n.alive = false; continue; }
        n.energy -= tx;
        ++r.controlTx;
        const double rx = RxEnergy(CONTROL_BITS);
        if (rx > nodes[c].energy) { nodes[c].energy = 0.0; nodes[c].alive = false; nodes[c].finalCH = false; continue; }
        nodes[c].energy -= rx;
        ++r.controlRx;
    }
    for (auto& c : nodes) {
        if (!c.alive || !c.finalCH) continue;
        double farthest = -1.0;
        for (const auto& m : nodes)
            if (m.alive && !m.finalCH && m.clusterHead == c.id) farthest = max(farthest, Dist(m, c));
        if (farthest < 0.0) continue;
        const double tx = TxEnergy(CONTROL_BITS, farthest);
        if (tx > c.energy) { c.energy = 0.0; c.alive = false; c.finalCH = false; continue; }
        c.energy -= tx;
        ++r.controlTx;
        for (auto& m : nodes) {
            if (!m.alive || m.finalCH || m.clusterHead != c.id) continue;
            const double rx = RxEnergy(CONTROL_BITS);
            if (rx > m.energy) { m.energy = 0.0; m.alive = false; continue; }
            m.energy -= rx;
            ++r.controlRx;
        }
    }
}

static RoundResult SimulateRound(vector<SensorNode>& nodes, uint32_t round, uint32_t heedIterations)
{
    RoundResult r;
    r.round = round;
    r.heedIterations = heedIterations;

    const double before = [&]() { double s = 0.0; for (const auto& n : nodes) s += n.energy; return s; }();

    // Setup control-energy cost (same accounting style as HEED, since the
    // Phase-1 iterative election is unchanged and drives this cost).
    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive) continue;
        double e = heedIterations * TxEnergy(CONTROL_BITS, RANGE);
        if (e >= nodes[i].energy) { nodes[i].energy = 0.0; nodes[i].alive = false; }
        else { nodes[i].energy -= e; r.controlTx += heedIterations; }
    }

    auto liveNb = BuildNeighbors(nodes);
    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive) continue;
        double e = static_cast<double>(liveNb[i].size()) * heedIterations * RxEnergy(CONTROL_BITS);
        if (e >= nodes[i].energy) { nodes[i].energy = 0.0; nodes[i].alive = false; }
        else { nodes[i].energy -= e; r.controlRx += static_cast<uint64_t>(liveNb[i].size()) * heedIterations; }
    }

    for (auto& n : nodes) if (!n.alive) n.finalCH = false;
    liveNb = BuildNeighbors(nodes);

    // Re-association after setup deaths -- SAME rule as Phase 2: nearest
    // distance, LEACH-style (not cost-based).
    for (auto& n : nodes) {
        if (!n.alive) { n.clusterHead = numeric_limits<uint32_t>::max(); continue; }
        if (n.finalCH) { n.clusterHead = n.id; continue; }

        double bestDistance = numeric_limits<double>::infinity();
        uint32_t bestCH = numeric_limits<uint32_t>::max();
        for (uint32_t c : liveNb[n.id]) {
            if (!nodes[c].alive || !nodes[c].finalCH) continue;
            const double d = Dist(n, nodes[c]);
            if (d < bestDistance - 1e-12 || (fabs(d - bestDistance) < 1e-12 && c < bestCH)) {
                bestDistance = d;
                bestCH = c;
            }
        }
        n.clusterHead = bestCH;
    }

    ChargeJoinAndSchedule(nodes, r);   // unified env: join request + TDMA schedule
    for (auto& n : nodes) if (!n.alive) n.finalCH = false;

    for (const auto& n : nodes) if (n.alive && n.finalCH) ++r.chCount;
    for (const auto& n : nodes) if (n.alive) ++r.generated;

    vector<uint32_t> membersPerCH(N, 0);
    vector<bool> memberDeliveredToCH(N, false);
    vector<double> delayToCH(N, 0.0);

    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive || nodes[i].finalCH) continue;
        uint32_t c = nodes[i].clusterHead;
        if (c >= N || !nodes[c].alive || !nodes[c].finalCH) { ++r.unclustered; continue; }
        double d = Dist(nodes[i], nodes[c]);
        if (d > RANGE) { ++r.unclustered; continue; }
        double tx = TxEnergy(PACKET_BITS, d);
        double rx = RxEnergy(PACKET_BITS);
        if (tx > nodes[i].energy || rx > nodes[c].energy) { ++r.lost; continue; }
        nodes[i].energy -= tx;
        nodes[c].energy -= rx;
        ++r.dataTx; ++r.dataRx;
        ++membersPerCH[c];
        memberDeliveredToCH[i] = true;
        delayToCH[i] = DelayMs(PACKET_BITS, d);
    }

    double delaySum = 0.0;
    uint32_t deliveredSources = 0;

    for (uint32_t c = 0; c < N; ++c) {
        if (!nodes[c].alive || !nodes[c].finalCH) continue;
        const uint32_t members = membersPerCH[c];
        const double agg = static_cast<double>(members + 1) * AggEnergy(PACKET_BITS);   // members + own signal (unified env)
        if (agg > nodes[c].energy) { ++r.lost; nodes[c].energy = 0.0; nodes[c].alive = false; continue; }
        nodes[c].energy -= agg;
        const double dBS = DistBS(nodes[c]);
        const double txBS = TxEnergy(PACKET_BITS, dBS);
        if (txBS > nodes[c].energy) { ++r.lost; nodes[c].energy = 0.0; nodes[c].alive = false; continue; }
        nodes[c].energy -= txBS;
        ++r.dataTx; ++r.dataRx;
        deliveredSources += members + 1;
        delaySum += DelayMs(PACKET_BITS, dBS);
        for (uint32_t i = 0; i < N; ++i)
            if (memberDeliveredToCH[i] && nodes[i].clusterHead == c)
                delaySum += delayToCH[i] + DelayMs(PACKET_BITS, dBS);
    }

    r.delivered = min(deliveredSources, r.generated);
    r.lost = r.generated - r.delivered;

    double after = 0.0;
    uint32_t assigned = 0;
    for (auto& n : nodes) {
        if (n.energy <= 0.0) { n.energy = 0.0; n.alive = false; }
        after += n.energy;
        if (n.alive) ++r.alive;
        if (n.alive && !n.finalCH && n.clusterHead < N &&
            nodes[n.clusterHead].alive && nodes[n.clusterHead].finalCH)
            ++assigned;
    }

    r.dead = N - r.alive;
    r.energyUsed = max(0.0, before - after);
    r.residualEnergy = after;
    r.avgClusterSize = r.chCount ? static_cast<double>(assigned + r.chCount) / r.chCount : 0.0;

    if (r.alive == 0) {
        r.chCount = 0; r.generated = 0; r.delivered = 0; r.lost = 0; r.unclustered = 0;
        r.avgClusterSize = 0.0; r.avgDelayMs = 0.0; r.pdr = 0.0; r.throughputKbps = 0.0;
    }

    r.pdr = r.generated ? static_cast<double>(r.delivered) / r.generated : 0.0;
    r.avgDelayMs = r.delivered ? delaySum / r.delivered : 0.0;

    const double controlTime = static_cast<double>(r.controlTx) * TxTimeSec(CONTROL_BITS);
    const double dataTxTime = static_cast<double>(r.dataTx) * TxTimeSec(PACKET_BITS);
    r.roundDurationSec = controlTime + dataTxTime;
    r.throughputKbps = r.roundDurationSec > 0.0
        ? static_cast<double>(r.delivered * PACKET_BITS) / r.roundDurationSec / 1000.0 : 0.0;

    return r;
}

static void InitSwitches(wsn::Hook& hook)
{
    CHARGE_HELLO = static_cast<int>(hook.Define("CHARGE_HELLO", 1));
}

static int Run(wsn::Hook& HOOK)
{
    InitSwitches(HOOK);
    HOOK.SetBaseStation(BSX, BSY);

    wsn::Out() << "\n========================================\n";
    wsn::Out() << "  HYBRID v1: LEACH clustering + HEED CH selection\n";
    wsn::Out() << "========================================\n";
    wsn::Out() << "Cprob=" << CPROB << " pMin=" << PMIN << " | Selection cost=1/(degree+1)\n";
    wsn::Out() << "Join rule = LEACH-style nearest distance (NOT cost-based)\n";
    wsn::Out() << "========================================\n";

    mt19937 rng(SEED);
    uniform_real_distribution<double> pos(0.0, AREA);
    vector<SensorNode> nodes(N);

    for (uint32_t i = 0; i < N; ++i) {
        nodes[i].id = i;
        nodes[i].x = pos(rng);
        nodes[i].y = pos(rng);
        nodes[i].energy = E0;
        nodes[i].alive = true;
    }

    ofstream positions(wsn::CsvPath("node-positions.csv"));
    positions << "Node,X,Y\n";
    for (const auto& n : nodes) positions << n.id << ',' << n.x << ',' << n.y << '\n';
    positions << N << ',' << BSX << ',' << BSY << '\n';
    positions.close();

    ofstream rounds(wsn::CsvPath("v1_heed_election_leach_join-results.csv"));
    ofstream energy(wsn::CsvPath("v1_heed_election_leach_join-node-energy.csv"));
    ofstream lifetime(wsn::CsvPath("v1_heed_election_leach_join-node-lifetime.csv"));
    if (!rounds || !energy || !lifetime) NS_FATAL_ERROR("Cannot create CSV output files.");

    rounds << "Round,Alive,Dead,CH_Count,Generated,Delivered,Lost,Unclustered,"
              "Selection_Iterations,Control_TX,Control_RX,Data_TX,Data_RX,"
              "Energy_Used_J,Residual_Energy_J,Avg_Cluster_Size,Avg_Delay_ms,"
              "PDR,Round_Duration_s,Throughput_kbps\n";
    energy << "Round,Node,Energy_J,Alive,Is_CH,ClusterHead\n";
    lifetime << "Node,Death_Round\n";

    uint32_t FND = 0, HND = 0, LND = 0;
    bool fnd = false, hnd = false;
    vector<uint32_t> deathRound(N, 0);
    uint64_t totalGenerated = 0, totalDelivered = 0;
    double totalUsed = 0.0;

    wsn::Out() << "\nSimulation starts...\n";

    if (CHARGE_HELLO) {   // neighbour discovery, once at deployment (see CHARGE_HELLO)
        for (uint32_t i = 0; i < N; ++i) {
            nodes[i].energy -= TxEnergy(CONTROL_BITS, RANGE);
            for (uint32_t j = 0; j < N; ++j)
                if (j != i && Dist(nodes[i], nodes[j]) <= RANGE) nodes[j].energy -= RxEnergy(CONTROL_BITS);
        }
    }

    for (uint32_t round = 1; round <= MAX_ROUNDS; ++round) {
        auto nb = BuildNeighbors(nodes);
        UpdateCost(nodes, nb);
        uint32_t iterations = RunHEED(nodes, nb, rng);
        RoundResult r = SimulateRound(nodes, round, iterations);
        HOOK.Round(round, r, nodes);   // OMNeT++: one round = one step of simulation time

        totalGenerated += r.generated;
        totalDelivered += r.delivered;
        totalUsed += r.energyUsed;

        rounds << fixed << setprecision(10)
               << r.round << ',' << r.alive << ',' << r.dead << ',' << r.chCount << ','
               << r.generated << ',' << r.delivered << ',' << r.lost << ',' << r.unclustered << ','
               << r.heedIterations << ',' << r.controlTx << ',' << r.controlRx << ','
               << r.dataTx << ',' << r.dataRx << ',' << r.energyUsed << ',' << r.residualEnergy << ','
               << r.avgClusterSize << ',' << r.avgDelayMs << ',' << r.pdr << ','
               << r.roundDurationSec << ',' << r.throughputKbps << '\n';

        for (const auto& n : nodes) {
            energy << round << ',' << n.id << ',' << setprecision(10) << n.energy << ','
                   << (n.alive ? 1 : 0) << ',' << (n.alive && n.finalCH ? 1 : 0) << ','
                   << (n.clusterHead < N ? to_string(n.clusterHead) : "-1") << '\n';
            if (!n.alive && deathRound[n.id] == 0) deathRound[n.id] = round;
        }

        if (!fnd && r.dead >= 1) { FND = round; fnd = true; }
        if (!hnd && r.alive <= N / 2) { HND = round; hnd = true; }

        wsn::Out() << fixed << setprecision(4)
             << "Round " << setw(4) << round << " | Alive=" << setw(3) << r.alive
             << " | CH=" << setw(3) << r.chCount << " | PDR=" << setw(7) << r.pdr
             << " | Residual=" << setw(9) << r.residualEnergy << " J\n";

        if (r.alive == 0) { LND = round; break; }
    }

    if (LND == 0) {
        for (const auto& n : nodes) if (n.alive) { LND = 0; break; }
        if (LND == 0) for (uint32_t d : deathRound) LND = max(LND, d);
    }

    for (uint32_t i = 0; i < N; ++i)
        lifetime << i << ',' << (deathRound[i] ? to_string(deathRound[i]) : "Not_Dead") << '\n';

    rounds.close(); energy.close(); lifetime.close();

    const double overallPdr = totalGenerated ? static_cast<double>(totalDelivered) / totalGenerated : 0.0;

    wsn::Out() << "\n========================================\n";
    wsn::Out() << "             FINAL RESULTS\n";
    wsn::Out() << "========================================\n";
    wsn::Out() << "FND = " << (fnd ? to_string(FND) : "Not reached") << " rounds\n";
    wsn::Out() << "HND = " << (hnd ? to_string(HND) : "Not reached") << " rounds\n";
    wsn::Out() << "LND = " << (LND ? to_string(LND) : "Not reached") << " rounds\n";
    wsn::Out() << fixed << setprecision(6);
    wsn::Out() << "Total Energy Used = " << totalUsed << " J\n";
    wsn::Out() << "Overall PDR = " << overallPdr << "\n";
    wsn::Out() << "\nCSV outputs: v1_heed_election_leach_join-results.csv, v1_heed_election_leach_join-node-energy.csv,\n";
    wsn::Out() << "             v1_heed_election_leach_join-node-lifetime.csv\n";
    wsn::Out() << "========================================\n";

    {   // OMNeT++: final metrics, exactly as computed above
        wsn::FinalView fv;
        fv.FND = fnd ? FND : 0; fv.HND = hnd ? HND : 0; fv.LND = LND;
        fv.pdr = overallPdr; fv.energyUsed = totalUsed;
        fv.generated = totalGenerated; fv.delivered = totalDelivered;
        HOOK.Finish(fv);
    }
    return 0;
}


} // namespace wsn_v1_heed_election_leach_join

static wsn::Registrar wsn_v1_heed_election_leach_join_registrar("v1_heed_election_leach_join", "code/4_PROPOSED/v1_heed_election_leach_join.cc", &wsn_v1_heed_election_leach_join::Run, {"CHARGE_HELLO"});
