// OMNeT++ port of code/4_PROPOSED/v5_backup_int15.cc (thesis ns-3 program).
// Generated by omnetpp/tools/port_ns3.py: the protocol logic below is the
// original code, unchanged; see the header of that script for what was adapted.

#include "WsnRuntime.h"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <random>
#include <string>
#include <vector>

using namespace std;

namespace wsn_v5_backup_int15 {

// ============================================================================
// HYBRID PROTOCOL v5: MULTI-ROUND CLUSTERING + BACKUP CH FAILOVER
// ns-3.41 / C++
//
// UNIFIED-ENVIRONMENT FIX (same rules as every baseline in code/2_EDITED):
//   - the CH advertisement is now sent at ADV_RANGE (field diagonal),
//     because every node in the field hears it and may join that CH
//     (it used to be charged at RANGE = 25 m only);
//   - join request (member -> CH) and TDMA schedule (CH -> farthest
//     member) are now charged at every setup round;
//   - the CH fuses members + its own signal (members + 1).
// RESULT of this exact file (seed 12345): FND 1513 / HND 2116 / LND 2356 / PDR 98.44%
// (Any other numbers quoted further down this header are from older
//  versions or Python pre-checks and are kept only as history.)
//
// SAME core design as v3 (confirmed via NS-3: FND=1730, HND=2081, LND=2703,
// PDR=97.72%) -- single-pass selection + 5-round multi-round reuse. This
// version adds ONE new mechanism on top, addressing a limitation v3's own
// header and results honestly disclosed:
//
//   4. BACKUP CH FAILOVER (NEW): v3's multi-round reuse means a CH that
//      dies mid-interval leaves its members "unclustered" (lost) until the
//      next scheduled setup round, up to SETUP_INTERVAL-1 rounds later.
//      v5 fixes this with a backup CH pre-designated AT ZERO EXTRA
//      MESSAGING COST: during the same single-pass score computation
//      already performed at setup time, each cluster's runner-up (highest
//      score among non-CH members) is remembered as that cluster's backup.
//      If the primary CH dies mid-interval, the backup is promoted
//      immediately -- but ONLY if it has enough energy to plausibly survive
//      CH duty for the rest of the interval (a naive promotion of an
//      under-resourced backup was found, via a Python pre-check, to trade
//      one dead CH for another without net benefit).
//
//   HONEST, DISCLOSED TRADE-OFF (found during the same Python pre-check):
//      the backup mechanism cuts "unclustered" incidents by roughly 55-60%
//      and improves PDR slightly, but LND itself was found to DECREASE by
//      roughly 8% relative to v3 without backups. The mechanism does not
//      eliminate energy cost -- it relocates a CH's remaining duty onto an
//      otherwise-ordinary member, which now depletes faster than it would
//      have as a plain member. Reliability improves; raw lifetime does not.
//      This is reported as a genuine finding, not hidden: the multi-round
//      reuse design has an inherent reliability/lifetime tension that no
//      zero-extra-cost fix fully removes.
// ============================================================================
//
//   1. CH SELECTION -- single-pass (NO iterative negotiation at all):
//        score_i = (E_i/E0) * (1 + degree_norm_i)   -- energy (HEED) x
//                                                        connectivity (HEED)
//        threshold t(r) = LEACH's rotation-guarantee formula
//        CHprob_i = t(r) * score_i, drawn ONCE per setup round.
//      This keeps HEED's "smart" energy+degree signal but removes the
//      expensive multi-iteration doubling loop entirely.
//
//   2. MULTI-ROUND REUSE (the main energy-saving mechanism):
//        CHs and cluster membership are only recomputed once every
//        SETUP_INTERVAL rounds (a "setup round"). The rounds in between
//        are pure DATA rounds: nodes just reuse last setup's assignment
//        and transmit -- ZERO control-message overhead. This mirrors
//        original LEACH's own paper structure (1 setup phase + several
//        steady-state frames per "round"), which none of our earlier
//        NS-3 files actually implemented (they recomputed clustering
//        every single round).
//
//   3. CLUSTERING (join): LEACH-style nearest-distance, unchanged from
//      v1/v2 (already shown to be low-cost and effective).
//
//   4. If a CH dies mid-interval, its members are simply unclustered
//      (lost) for the remaining rounds until the next setup -- a
//      realistic, honestly-reported limitation of multi-round reuse.
//
// Exports node-positions.csv for the Python cluster-circle visualizer.
// No WiFi/packet layer (reliable, analytical-only design).
// ============================================================================

struct SensorNode {
    uint32_t id = 0;
    double x = 0.0;
    double y = 0.0;
    double energy = 0.0;
    bool alive = true;
    bool finalCH = false;
    uint32_t clusterHead = numeric_limits<uint32_t>::max();
    bool selectedThisEpoch = false;
    uint32_t degree = 0;
    uint32_t backupOf = numeric_limits<uint32_t>::max(); // NEW: this node is the pre-designated
                                                          // backup CH for cluster head `backupOf`
    bool usedAsBackupThisInterval = false;               // NEW: prevents a backup being promoted twice
};

struct RoundResult {
    uint32_t round = 0;
    uint32_t alive = 0;
    uint32_t dead = 0;
    uint32_t chCount = 0;
    uint32_t generated = 0;
    uint32_t delivered = 0;
    uint32_t lost = 0;
    uint32_t unclustered = 0;
    uint64_t controlTx = 0;
    uint64_t controlRx = 0;
    uint64_t dataTx = 0;
    uint64_t dataRx = 0;
    double energyUsed = 0.0;
    double residualEnergy = 0.0;
    double avgClusterSize = 0.0;
    double avgDelayMs = 0.0;
    double pdr = 0.0;
    double throughputKbps = 0.0;
    double roundDurationSec = 0.0;
    bool wasSetupRound = false;
    uint32_t backupPromotions = 0;   // NEW: how many backup CHs were promoted this round
    uint32_t rejectedPromotions = 0; // NEW: how many promotions were skipped (insufficient energy)
};

// ----------------------------- Network -------------------------------------
static constexpr uint32_t N = 100;
static constexpr double AREA = 100.0;
static const double ADV_RANGE = AREA * std::sqrt(2.0); // CH advertisement heard by the whole field (unified env)
static constexpr double BSX = 50.0;
static constexpr double BSY = 50.0;
static constexpr double E0 = 0.5;
static constexpr double RANGE = 25.0;

// ------------------------------- Protocol params ----------------------------
static constexpr double P_CH = 0.05;          // same target ratio as LEACH
static constexpr uint32_t EPOCH = 20;         // LEACH-style fairness window (1/P_CH)
static constexpr uint32_t SETUP_INTERVAL = 15; // CHANGED (was 5): a longer interval saves even more
                                                // control overhead. Tested alone (v4, no backup) this
                                                // REGRESSED badly (LND 2703->2521) because a dead CH
                                                // left members unclustered for up to 14 rounds. Combined
                                                // WITH the backup-CH mechanism above, a Python pre-check
                                                // found this recovers LND close to v3's original 5-round
                                                // baseline while further improving PDR over the plain
                                                // 15-round-no-backup attempt.
static constexpr double BACKUP_SAFETY_MARGIN = 1.0; // NEW: backup only promoted if its energy
                                                     // covers >= this factor x estimated cost
                                                     // for the rest of the current interval

// --------------------------- Radio / traffic -------------------------------
static constexpr uint32_t PACKET_BITS = 2000;
// Neighbour discovery is charged once, at deployment: every node broadcasts one
// HELLO control frame over the neighbour range and receives its neighbours' HELLOs
// (-DCHARGE_HELLO=0 switches it off). The nodes are static, so the list is reused;
// a neighbour that dies is noticed from its silence (no extra message).
static int CHARGE_HELLO = 1;   // switch (ini: defines = "CHARGE_HELLO=...")
static constexpr uint32_t CONTROL_BITS = 200;
static constexpr double E_ELEC = 50e-9;
static constexpr double E_FS = 10e-12;
static constexpr double E_MP = 0.0013e-12;
static constexpr double E_DA = 5e-9;
static constexpr double DATA_RATE = 250000.0;
static constexpr double LIGHT = 3.0e8;

static constexpr uint32_t MAX_ROUNDS = 5000;  // RAISED from 3000 as a safety margin for interval=15
static constexpr uint32_t SEED = 12345;

// ----------------------------- Geometry ------------------------------------
static double Dist(const SensorNode& a, const SensorNode& b) { return hypot(a.x - b.x, a.y - b.y); }
static double DistBS(const SensorNode& a) { return hypot(a.x - BSX, a.y - BSY); }
static double D0() { return sqrt(E_FS / E_MP); }

static double TxEnergy(uint32_t bits, double d)
{
    if (d <= 0.0) return bits * E_ELEC;
    if (d < D0()) return bits * (E_ELEC + E_FS * d * d);
    return bits * (E_ELEC + E_MP * pow(d, 4.0));
}
static double RxEnergy(uint32_t bits) { return bits * E_ELEC; }
static double AggEnergy(uint32_t bits) { return bits * E_DA; }
static double TxTimeSec(uint32_t bits) { return static_cast<double>(bits) / DATA_RATE; }
static double DelayMs(uint32_t bits, double d) { return (TxTimeSec(bits) + d / LIGHT) * 1000.0; }

static vector<vector<uint32_t>> BuildNeighbors(const vector<SensorNode>& nodes)
{
    vector<vector<uint32_t>> nb(N);
    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive) continue;
        for (uint32_t j = 0; j < N; ++j) {
            if (i == j || !nodes[j].alive) continue;
            if (Dist(nodes[i], nodes[j]) <= RANGE) nb[i].push_back(j);
        }
    }
    return nb;
}

static double Threshold(uint32_t setupIndex)
{
    // Same LEACH-style rotation-guarantee formula, applied per SETUP round
    // index (not per data round) since selection only happens at setups.
    const uint32_t r = setupIndex % EPOCH;
    const double denom = 1.0 - P_CH * static_cast<double>(r);
    return denom > 0.0 ? P_CH / denom : 1.0;
}

// --------------------- SINGLE-PASS selection (no iteration) ----------------
static uint32_t RunSelection(vector<SensorNode>& nodes, const vector<vector<uint32_t>>& nb,
                              uint32_t setupIndex, mt19937& rng)
{
    uniform_real_distribution<double> U(0.0, 1.0);

    for (auto& n : nodes) { n.finalCH = false; n.clusterHead = numeric_limits<uint32_t>::max(); }

    if (setupIndex % EPOCH == 0)
        for (auto& n : nodes) n.selectedThisEpoch = false;

    uint32_t maxDegree = 1;
    for (uint32_t i = 0; i < N; ++i) {
        nodes[i].degree = nodes[i].alive ? static_cast<uint32_t>(nb[i].size()) : 0;
        maxDegree = max(maxDegree, nodes[i].degree);
    }

    const double t = Threshold(setupIndex);
    vector<uint32_t> candidates;

    for (auto& n : nodes) {
        if (!n.alive || n.selectedThisEpoch) continue;
        const double degreeNorm = static_cast<double>(n.degree) / static_cast<double>(maxDegree);
        const double score = (n.energy / E0) * (1.0 + degreeNorm);  // HEED energy x connectivity, ONE shot
        const double prob = min(1.0, t * score);
        if (U(rng) <= prob) candidates.push_back(n.id);
    }

    if (candidates.empty()) {
        vector<uint32_t> eligible;
        for (const auto& n : nodes) if (n.alive && !n.selectedThisEpoch) eligible.push_back(n.id);
        if (!eligible.empty()) {
            uint32_t best = eligible.front();
            double bestScore = -1.0;
            for (uint32_t id : eligible) {
                double degreeNorm = static_cast<double>(nodes[id].degree) / static_cast<double>(maxDegree);
                double score = (nodes[id].energy / E0) * (1.0 + degreeNorm);
                if (score > bestScore) { bestScore = score; best = id; }
            }
            candidates.push_back(best);
        }
    }

    for (uint32_t id : candidates) { nodes[id].finalCH = true; nodes[id].selectedThisEpoch = true; }

    uint32_t chCount = 0;
    for (const auto& n : nodes) if (n.alive && n.finalCH) ++chCount;

    // ---- LEACH-style nearest-distance join ----
    for (auto& n : nodes) {
        n.clusterHead = numeric_limits<uint32_t>::max();
        if (!n.alive) continue;
        if (n.finalCH) { n.clusterHead = n.id; continue; }

        double bestDistance = numeric_limits<double>::infinity();
        uint32_t bestCH = numeric_limits<uint32_t>::max();
        for (const auto& c : nodes) {
            if (!c.alive || !c.finalCH) continue;
            const double d = Dist(n, c);
            if (d < bestDistance - 1e-12 || (fabs(d - bestDistance) < 1e-12 && c.id < bestCH)) {
                bestDistance = d;
                bestCH = c.id;
            }
        }
        if (bestCH != numeric_limits<uint32_t>::max()) n.clusterHead = bestCH;
    }

    // ---- NEW: pre-designate a backup CH per cluster, at ZERO extra messaging
    // cost -- the score used here was already computed above for every node
    // during this same single-pass selection; we simply also remember each
    // cluster's runner-up. In a real deployment this ID would be piggybacked
    // on the CH's own setup-round advertisement, so members already know who
    // to fail over to without any additional control message. ----
    for (auto& n : nodes) { n.backupOf = numeric_limits<uint32_t>::max(); n.usedAsBackupThisInterval = false; }
    for (const auto& ch : nodes) {
        if (!ch.alive || !ch.finalCH) continue;
        uint32_t bestBackup = numeric_limits<uint32_t>::max();
        double bestScore = -1.0;
        for (const auto& m : nodes) {
            if (!m.alive || m.finalCH || m.clusterHead != ch.id) continue;
            const double degreeNorm = static_cast<double>(m.degree) / static_cast<double>(maxDegree);
            const double score = (m.energy / E0) * (1.0 + degreeNorm);
            if (score > bestScore) { bestScore = score; bestBackup = m.id; }
        }
        if (bestBackup != numeric_limits<uint32_t>::max()) nodes[bestBackup].backupOf = ch.id;
    }

    return chCount;
}

// ---------------------------- Round simulation -----------------------------
// ---- Unified environment (same rules as every baseline) ----
// After the CH advertisements, every member sends a JOIN request to its CH,
// and every CH sends ONE TDMA schedule that must reach its farthest member.
static void ChargeJoinAndSchedule(vector<SensorNode>& nodes, RoundResult& r)
{
    for (auto& n : nodes) {
        if (!n.alive || n.finalCH) continue;
        const uint32_t c = n.clusterHead;
        if (c >= N || !nodes[c].alive || !nodes[c].finalCH) continue;
        const double tx = TxEnergy(CONTROL_BITS, Dist(n, nodes[c]));
        if (tx > n.energy) { n.energy = 0.0; n.alive = false; continue; }
        n.energy -= tx;
        ++r.controlTx;
        const double rx = RxEnergy(CONTROL_BITS);
        if (rx > nodes[c].energy) { nodes[c].energy = 0.0; nodes[c].alive = false; nodes[c].finalCH = false; continue; }
        nodes[c].energy -= rx;
        ++r.controlRx;
    }
    for (auto& c : nodes) {
        if (!c.alive || !c.finalCH) continue;
        double farthest = -1.0;
        for (const auto& m : nodes)
            if (m.alive && !m.finalCH && m.clusterHead == c.id) farthest = max(farthest, Dist(m, c));
        if (farthest < 0.0) continue;
        const double tx = TxEnergy(CONTROL_BITS, farthest);
        if (tx > c.energy) { c.energy = 0.0; c.alive = false; c.finalCH = false; continue; }
        c.energy -= tx;
        ++r.controlTx;
        for (auto& m : nodes) {
            if (!m.alive || m.finalCH || m.clusterHead != c.id) continue;
            const double rx = RxEnergy(CONTROL_BITS);
            if (rx > m.energy) { m.energy = 0.0; m.alive = false; continue; }
            m.energy -= rx;
            ++r.controlRx;
        }
    }
}

static RoundResult SimulateRound(vector<SensorNode>& nodes, uint32_t round, bool isSetupRound)
{
    RoundResult r;
    r.round = round;
    r.wasSetupRound = isSetupRound;

    const double before = [&]() { double s = 0.0; for (const auto& n : nodes) s += n.energy; return s; }();

    // ---- Control overhead ONLY on setup rounds (the key saving) ----
    if (isSetupRound) {
        for (uint32_t c = 0; c < N; ++c) {
            if (!nodes[c].alive || !nodes[c].finalCH) continue;
            const double tx = TxEnergy(CONTROL_BITS, ADV_RANGE);   // unified env: every node hears it and may join
            if (tx > nodes[c].energy) { nodes[c].energy = 0.0; nodes[c].alive = false; nodes[c].finalCH = false; continue; }
            nodes[c].energy -= tx;
            ++r.controlTx;
            for (uint32_t v = 0; v < N; ++v) {
                if (v == c || !nodes[v].alive) continue;
                const double rx = RxEnergy(CONTROL_BITS);
                if (rx > nodes[v].energy) { nodes[v].energy = 0.0; nodes[v].alive = false; nodes[v].finalCH = false; continue; }
                nodes[v].energy -= rx;
                ++r.controlRx;
            }
        }

        for (auto& n : nodes) if (!n.alive) n.finalCH = false;

        for (auto& n : nodes) {
            n.clusterHead = numeric_limits<uint32_t>::max();
            if (!n.alive) continue;
            if (n.finalCH) { n.clusterHead = n.id; continue; }
            double bestDistance = numeric_limits<double>::infinity();
            uint32_t bestCH = numeric_limits<uint32_t>::max();
            for (const auto& c : nodes) {
                if (!c.alive || !c.finalCH) continue;
                const double d = Dist(n, c);
                if (d < bestDistance - 1e-12 || (fabs(d - bestDistance) < 1e-12 && c.id < bestCH)) {
                    bestDistance = d;
                    bestCH = c.id;
                }
            }
            n.clusterHead = bestCH;
        }
    }

    if (isSetupRound) {   // unified env: join request + TDMA schedule
        ChargeJoinAndSchedule(nodes, r);
        for (auto& n : nodes) if (!n.alive) n.finalCH = false;
    }

    // ---- Every round: handle CHs that died mid-interval (between setups) ----
    // NEW: before giving up and disconnecting members, try promoting the
    // pre-designated backup CH -- but ONLY if it has enough energy to cover
    // the estimated cost of surviving CH duty for the rest of this interval.
    // Promoting an under-resourced backup would just kill it prematurely too,
    // trading one dead CH for another without truly fixing anything.
    // Dead CHs are detected via orphaned membership (clusterHead points to a
    // dead node) rather than the finalCH flag, since finalCH is already
    // cleared to false at the moment a node dies elsewhere in this function.
    const uint32_t roundsLeftInInterval = SETUP_INTERVAL - ((round - 1) % SETUP_INTERVAL);
    vector<uint32_t> orphanedCHs;
    for (const auto& n : nodes) {
        if (n.alive && n.clusterHead < N && !nodes[n.clusterHead].alive) {
            if (find(orphanedCHs.begin(), orphanedCHs.end(), n.clusterHead) == orphanedCHs.end())
                orphanedCHs.push_back(n.clusterHead);
        }
    }

    for (uint32_t c : orphanedCHs) {
        uint32_t backupId = numeric_limits<uint32_t>::max();
        for (const auto& m : nodes) {
            if (m.backupOf == c) { backupId = m.id; break; }
        }

        bool promoted = false;
        if (backupId != numeric_limits<uint32_t>::max()
            && nodes[backupId].alive && !nodes[backupId].finalCH
            && !nodes[backupId].usedAsBackupThisInterval) {

            uint32_t estMembers = 1;
            for (const auto& m : nodes) if (m.alive && m.clusterHead == c) ++estMembers;
            const double estCostPerRound = static_cast<double>(estMembers) * AggEnergy(PACKET_BITS)
                                          + TxEnergy(PACKET_BITS, DistBS(nodes[backupId]));
            const double estTotalNeed = BACKUP_SAFETY_MARGIN * estCostPerRound
                                       * static_cast<double>(roundsLeftInInterval);

            if (nodes[backupId].energy >= estTotalNeed) {
                nodes[backupId].finalCH = true;
                nodes[backupId].usedAsBackupThisInterval = true;
                nodes[backupId].clusterHead = backupId;
                for (auto& m : nodes) {
                    if (m.alive && m.clusterHead == c) m.clusterHead = backupId;
                }
                ++r.backupPromotions;
                promoted = true;
            } else {
                ++r.rejectedPromotions;
            }
        }
        if (!promoted) {
            for (auto& n : nodes) {
                if (n.alive && n.clusterHead == c) n.clusterHead = numeric_limits<uint32_t>::max();
            }
        }
    }
    for (auto& n : nodes) {
        if (n.alive && n.clusterHead < N && !nodes[n.clusterHead].alive)
            n.clusterHead = numeric_limits<uint32_t>::max();
    }

    for (const auto& n : nodes) if (n.alive && n.finalCH) ++r.chCount;
    for (const auto& n : nodes) if (n.alive) ++r.generated;

    vector<uint32_t> membersPerCH(N, 0);
    vector<bool> memberDelivered(N, false);
    vector<double> delayToCH(N, 0.0);

    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive || nodes[i].finalCH) continue;
        const uint32_t c = nodes[i].clusterHead;
        if (c >= N || !nodes[c].alive || !nodes[c].finalCH) { ++r.unclustered; continue; }
        const double d = Dist(nodes[i], nodes[c]);
        const double tx = TxEnergy(PACKET_BITS, d);
        const double rx = RxEnergy(PACKET_BITS);
        if (tx > nodes[i].energy || rx > nodes[c].energy) { ++r.lost; continue; }
        nodes[i].energy -= tx;
        nodes[c].energy -= rx;
        ++r.dataTx; ++r.dataRx;
        ++membersPerCH[c];
        memberDelivered[i] = true;
        delayToCH[i] = DelayMs(PACKET_BITS, d);
    }

    double delaySum = 0.0;
    uint32_t deliveredSources = 0;

    for (uint32_t c = 0; c < N; ++c) {
        if (!nodes[c].alive || !nodes[c].finalCH) continue;
        const uint32_t members = membersPerCH[c];
        const double agg = static_cast<double>(members + 1) * AggEnergy(PACKET_BITS);   // members + own signal (unified env)
        if (agg > nodes[c].energy) { nodes[c].energy = 0.0; nodes[c].alive = false; nodes[c].finalCH = false; ++r.lost; continue; }
        nodes[c].energy -= agg;
        const double dBS = DistBS(nodes[c]);
        const double txBS = TxEnergy(PACKET_BITS, dBS);
        if (txBS > nodes[c].energy) { nodes[c].energy = 0.0; nodes[c].alive = false; nodes[c].finalCH = false; ++r.lost; continue; }
        nodes[c].energy -= txBS;
        ++r.dataTx; ++r.dataRx;
        deliveredSources += members + 1;
        delaySum += DelayMs(PACKET_BITS, dBS);
        for (uint32_t i = 0; i < N; ++i)
            if (memberDelivered[i] && nodes[i].clusterHead == c)
                delaySum += delayToCH[i] + DelayMs(PACKET_BITS, dBS);
    }

    r.delivered = min(deliveredSources, r.generated);
    r.lost = r.generated - r.delivered;

    double after = 0.0;
    uint32_t assigned = 0;
    r.alive = 0;
    for (auto& n : nodes) {
        if (n.energy <= 0.0) { n.energy = 0.0; n.alive = false; n.finalCH = false; }
        after += n.energy;
        if (n.alive) ++r.alive;
        if (n.alive && !n.finalCH && n.clusterHead < N && nodes[n.clusterHead].alive && nodes[n.clusterHead].finalCH)
            ++assigned;
    }

    r.dead = N - r.alive;
    r.energyUsed = max(0.0, before - after);
    r.residualEnergy = after;
    r.avgClusterSize = r.chCount ? static_cast<double>(assigned + r.chCount) / r.chCount : 0.0;

    if (r.alive == 0) {
        r.chCount = 0; r.generated = 0; r.delivered = 0; r.lost = 0; r.unclustered = 0;
        r.avgClusterSize = 0.0; r.avgDelayMs = 0.0; r.pdr = 0.0; r.throughputKbps = 0.0;
    }

    r.pdr = r.generated ? static_cast<double>(r.delivered) / r.generated : 0.0;
    r.avgDelayMs = r.delivered ? delaySum / r.delivered : 0.0;

    const double controlTime = static_cast<double>(r.controlTx) * TxTimeSec(CONTROL_BITS);
    const double dataTxTime = static_cast<double>(r.dataTx) * TxTimeSec(PACKET_BITS);
    r.roundDurationSec = controlTime + dataTxTime;
    r.throughputKbps = r.roundDurationSec > 0.0
        ? static_cast<double>(r.delivered * PACKET_BITS) / r.roundDurationSec / 1000.0 : 0.0;

    return r;
}

static void InitSwitches(wsn::Hook& hook)
{
    CHARGE_HELLO = static_cast<int>(hook.Define("CHARGE_HELLO", 1));
}

static int Run(wsn::Hook& HOOK)
{
    InitSwitches(HOOK);
    HOOK.SetBaseStation(BSX, BSY);

    wsn::Out() << "\n========================================\n";
    wsn::Out() << "  HYBRID v5: Multi-Round Clustering + Backup CH Failover\n";
    wsn::Out() << "========================================\n";
    wsn::Out() << "Setup interval = " << SETUP_INTERVAL << " rounds (control overhead paid once per interval)\n";
    wsn::Out() << "Selection = single-pass energy x connectivity score (no iteration)\n";
    wsn::Out() << "Join = LEACH-style nearest distance\n";
    wsn::Out() << "========================================\n";

    mt19937 topologyRng(SEED);
    mt19937 electionRng(SEED + 1);
    uniform_real_distribution<double> pos(0.0, AREA);
    vector<SensorNode> nodes(N);

    for (uint32_t i = 0; i < N; ++i) {
        nodes[i].id = i;
        nodes[i].x = pos(topologyRng);
        nodes[i].y = pos(topologyRng);
        nodes[i].energy = E0;
        nodes[i].alive = true;
    }

    ofstream positions(wsn::CsvPath("node-positions.csv"));
    positions << "Node,X,Y\n";
    for (const auto& n : nodes) positions << n.id << ',' << n.x << ',' << n.y << '\n';
    positions << N << ',' << BSX << ',' << BSY << '\n';
    positions.close();

    ofstream rounds(wsn::CsvPath("v5_backup_int15-results.csv"));
    ofstream energy(wsn::CsvPath("v5_backup_int15-node-energy.csv"));
    ofstream lifetime(wsn::CsvPath("v5_backup_int15-node-lifetime.csv"));
    if (!rounds || !energy || !lifetime) NS_FATAL_ERROR("Cannot create CSV output files.");

    rounds << "Round,Alive,Dead,CH_Count,Generated,Delivered,Lost,Unclustered,"
              "Was_Setup_Round,Control_TX,Control_RX,Data_TX,Data_RX,"
              "Energy_Used_J,Residual_Energy_J,Avg_Cluster_Size,Avg_Delay_ms,"
              "PDR,Round_Duration_s,Throughput_kbps,Backup_Promotions,Rejected_Promotions\n";
    energy << "Round,Node,Energy_J,Alive,Is_CH,ClusterHead\n";
    lifetime << "Node,Death_Round\n";

    uint32_t FND = 0, HND = 0, LND = 0;
    bool fnd = false, hnd = false;
    vector<uint32_t> deathRound(N, 0);
    uint64_t totalGenerated = 0, totalDelivered = 0;
    uint64_t totalPromotions = 0, totalRejectedPromotions = 0;
    double totalUsed = 0.0;
    uint32_t setupIndex = 0;

    wsn::Out() << "\nSimulation starts...\n";

    if (CHARGE_HELLO) {   // neighbour discovery, once at deployment (see CHARGE_HELLO)
        for (uint32_t i = 0; i < N; ++i) {
            nodes[i].energy -= TxEnergy(CONTROL_BITS, RANGE);
            for (uint32_t j = 0; j < N; ++j)
                if (j != i && Dist(nodes[i], nodes[j]) <= RANGE) nodes[j].energy -= RxEnergy(CONTROL_BITS);
        }
    }

    for (uint32_t round = 1; round <= MAX_ROUNDS; ++round) {
        const bool isSetupRound = ((round - 1) % SETUP_INTERVAL == 0);

        if (isSetupRound) {
            auto nb = BuildNeighbors(nodes);
            RunSelection(nodes, nb, setupIndex, electionRng);
            ++setupIndex;
        }

        RoundResult r = SimulateRound(nodes, round, isSetupRound);
        HOOK.Round(round, r, nodes);   // OMNeT++: one round = one step of simulation time

        totalGenerated += r.generated;
        totalDelivered += r.delivered;
        totalUsed += r.energyUsed;
        totalPromotions += r.backupPromotions;
        totalRejectedPromotions += r.rejectedPromotions;

        rounds << fixed << setprecision(10)
               << r.round << ',' << r.alive << ',' << r.dead << ',' << r.chCount << ','
               << r.generated << ',' << r.delivered << ',' << r.lost << ',' << r.unclustered << ','
               << (r.wasSetupRound ? 1 : 0) << ',' << r.controlTx << ',' << r.controlRx << ','
               << r.dataTx << ',' << r.dataRx << ',' << r.energyUsed << ',' << r.residualEnergy << ','
               << r.avgClusterSize << ',' << r.avgDelayMs << ',' << r.pdr << ','
               << r.roundDurationSec << ',' << r.throughputKbps << ','
               << r.backupPromotions << ',' << r.rejectedPromotions << '\n';

        for (const auto& n : nodes) {
            energy << round << ',' << n.id << ',' << setprecision(10) << n.energy << ','
                   << (n.alive ? 1 : 0) << ',' << (n.alive && n.finalCH ? 1 : 0) << ','
                   << (n.clusterHead < N ? to_string(n.clusterHead) : "-1") << '\n';
            if (!n.alive && deathRound[n.id] == 0) deathRound[n.id] = round;
        }

        if (!fnd && r.dead >= 1) { FND = round; fnd = true; }
        if (!hnd && r.alive <= N / 2) { HND = round; hnd = true; }

        wsn::Out() << fixed << setprecision(4)
             << "Round " << setw(4) << round << (r.wasSetupRound ? "*" : " ")
             << " | Alive=" << setw(3) << r.alive << " | CH=" << setw(3) << r.chCount
             << " | PDR=" << setw(7) << r.pdr << " | Residual=" << setw(9) << r.residualEnergy << " J\n";

        if (r.alive == 0) { LND = round; break; }
    }

    if (LND == 0) {
        for (const auto& n : nodes) if (n.alive) { LND = 0; break; }
        if (LND == 0) for (uint32_t d : deathRound) LND = max(LND, d);
    }

    for (uint32_t i = 0; i < N; ++i)
        lifetime << i << ',' << (deathRound[i] ? to_string(deathRound[i]) : "Not_Dead") << '\n';

    rounds.close(); energy.close(); lifetime.close();

    const double overallPdr = totalGenerated ? static_cast<double>(totalDelivered) / totalGenerated : 0.0;

    wsn::Out() << "\n========================================\n";
    wsn::Out() << "             FINAL RESULTS\n";
    wsn::Out() << "========================================\n";
    wsn::Out() << "FND = " << (fnd ? to_string(FND) : "Not reached") << " rounds\n";
    wsn::Out() << "HND = " << (hnd ? to_string(HND) : "Not reached") << " rounds\n";
    wsn::Out() << "LND = " << (LND ? to_string(LND) : "Not reached") << " rounds\n";
    wsn::Out() << fixed << setprecision(6);
    wsn::Out() << "Total Energy Used = " << totalUsed << " J\n";
    wsn::Out() << "Overall PDR = " << overallPdr << "\n";
    wsn::Out() << "Backup CH Promotions = " << totalPromotions << " (successful) / "
         << totalRejectedPromotions << " (rejected -- insufficient energy)\n";
    wsn::Out() << "\nCSV outputs: v5_backup_int15-results.csv, v5_backup_int15-node-energy.csv,\n";
    wsn::Out() << "             v5_backup_int15-node-lifetime.csv\n";
    wsn::Out() << "========================================\n";

    {   // OMNeT++: final metrics, exactly as computed above
        wsn::FinalView fv;
        fv.FND = fnd ? FND : 0; fv.HND = hnd ? HND : 0; fv.LND = LND;
        fv.pdr = overallPdr; fv.energyUsed = totalUsed;
        fv.generated = totalGenerated; fv.delivered = totalDelivered;
        HOOK.Finish(fv);
        HOOK.Scalar("totalPromotions", static_cast<double>(totalPromotions));
        HOOK.Scalar("totalRejectedPromotions", static_cast<double>(totalRejectedPromotions));
    }
    return 0;
}


} // namespace wsn_v5_backup_int15

static wsn::Registrar wsn_v5_backup_int15_registrar("v5_backup_int15", "code/4_PROPOSED/v5_backup_int15.cc", &wsn_v5_backup_int15::Run, {"CHARGE_HELLO"});
