// OMNeT++ port of code/1_ORIGINAL/heed_ORIGINAL.cc (thesis ns-3 program).
// Generated by omnetpp/tools/port_ns3.py: the protocol logic below is the
// original code, unchanged; see the header of that script for what was adapted.

#include "WsnRuntime.h"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <random>
#include <string>
#include <vector>

using namespace std;

namespace wsn_heed_ORIGINAL {
// ============================================================================
// HEED -- ORIGINAL (paper-faithful reproduction)
// ns-3.41 / C++
//
// Matches Younis & Fahmy (2004), specifically Table 2 of their "Clustering
// Applications" section (the gen-LEACH comparison, closest to a concrete,
// numeric parameter set in the paper):
//   - Sink at (50,175) -- FAR from the network, not centered.
//   - Initial energy = 2 J/battery (paper's value, not 0.5J).
//   - Data packet = 800 bits (100 bytes, paper's value, not 2000 bits).
//   - Control/broadcast packet = 200 bits (25 bytes) -- already matched.
//   - Cprob=0.05, pmin=0.0005 (paper's stated defaults).
//   - Threshold distance d0 hardcoded to 75m (paper's stated value).
//   - Radio constants Eelec/Efs/Emp already matched the shared model exactly
//     (this is a genuine match, not an adjustment).
//   - Cost = 1/(degree+1) (favors high-degree nodes): this is explicitly
//     one of the paper's own two supported configurations (Table 1,
//     "Dense clusters" goal, "Same power" column -> "1/node degree").
//   PAPER-FIDELITY FIXES (this revision):
//   - Number of nodes: the paper's application experiments use 300-700
//     nodes (Fig. 8a-c) and 500 nodes (Fig. 8d); N = 500 here.
//   - Data packet = 100-byte payload + 25-byte header = 1000 bits (Table 2).
//   - One round (T_NO) = 5 TDM frames: clustering runs once per round, then
//     every node sends data 5 times (Table 2, "Round (T_NO) 5 TDM frames").
//   - HEED election follows the paper's pseudocode (Fig. 2) exactly: no
//     extra random pre-election, per-node termination one step after
//     CH_prob reaches 1, final/tentative announcements, and Phase III
//     ("uncovered" nodes announce themselves final CH).
//   - Control-message energy follows Lemma 4: each node broadcasts its cost
//     once (Phase I); ONLY nodes that announce themselves (tentative/final
//     CH) transmit in Phase II; a regular node stays silent until it sends
//     one join message to its CH.
//   - Data fusion: members' signals + the CH's own (5 nJ/bit/signal).
// For the version made directly comparable with LEACH/SH-LEACH/EECH-HEED
// under one shared environment, see heed_EDITED_unified.cc.
// ============================================================================

// ============================================================================
// HEED ALGORITHMIC BASELINE - "ORIGINAL HEED" (bug-fixed, no added algorithm)
// ns-3.41 / C++
//
// This is the "Original HEED" reference baseline for the thesis -- it
// contains ONLY corrections to implementation bugs/misconfigurations
// relative to the published HEED algorithm (Younis & Fahmy, 2004). It
// does NOT contain any new algorithmic mechanism beyond original HEED.
//
//  FIX 1 -- Cost function corrected:
//    The original code used cost = degree (raw), and BestCH() picks
//    MINIMUM cost, so the LEAST-connected node always won the local
//    competition -- backwards from HEED's intent (the secondary
//    parameter, approximating AMRP, should favor well-connected/cheap-
//    to-reach nodes). This produced many small, scattered clusters
//    (~10-13 CHs) regardless of CPROB.
//    Fix: cost = 1/(degree+1), so MINIMUM cost now corresponds to
//    MAXIMUM degree -- well-connected hub nodes win, matching HEED's
//    intended behavior more faithfully.
//
//  FIX 2 -- CPROB restored to its original 0.20 / pMin 0.05:
//    (A separate experiment temporarily lowered CPROB to 0.05 to test a
//    -- ultimately incorrect -- hypothesis that CPROB directly controls
//    final CH count. It does not: chProb doubles every iteration until
//    reaching 1.0 regardless of its starting value, so CPROB only
//    controls how many iterations/how much control overhead is spent
//    converging, not the final CH count. Lower CPROB just wastes energy
//    on extra iterations. Restored to 0.20 here.)
//
// Validated result with these two fixes only (SEED=12345):
//    FND = 323, HND = 570, LND = 1362, PDR = 99.69%
//
// NOTE: A further "rotation-fairness" mechanism (penalizing nodes that
// have served as CH many times) was explored separately to address a
// hotspot/early-death issue with frequently-selected hub nodes. That
// mechanism is NOT part of published HEED and is kept in a separate file
// (heed_ROTATION_FIX.cc) labeled as a distinct "Modified HEED" variant,
// so this file can be cited as a faithful "Original HEED" baseline.
//
// Purpose:
//   A reproducible algorithmic HEED baseline for energy-efficiency studies.
//
// Important scope:
//   This file does NOT model LR-WPAN PHY/MAC packets. Connectivity is based on
//   distance and energy is calculated with the first-order radio model.
//   PDR, delay and throughput are therefore analytical/model-level metrics,
//   not packet-level ns-3 measurements.
// ============================================================================

struct SensorNode {
    uint32_t id = 0;
    double x = 0.0;
    double y = 0.0;
    double energy = 0.0;
    bool alive = true;
    bool tentative = false;
    bool finalCH = false;
    uint32_t clusterHead = numeric_limits<uint32_t>::max();
    uint32_t degree = 0;
    double cost = 0.0;
    double chProb = 0.0;
};

struct RoundResult {
    uint32_t round = 0;
    uint32_t alive = 0;
    uint32_t dead = 0;
    uint32_t chCount = 0;
    uint32_t generated = 0;
    uint32_t delivered = 0;
    uint32_t lost = 0;
    uint32_t unclustered = 0;
    uint64_t controlTx = 0;
    uint64_t controlRx = 0;
    uint64_t dataTx = 0;
    uint64_t dataRx = 0;
    double energyUsed = 0.0;
    double residualEnergy = 0.0;
    double avgClusterSize = 0.0;
    double avgDelayMs = 0.0;
    double pdr = 0.0;
    double throughputKbps = 0.0;
    double roundDurationSec = 0.0;
    uint32_t heedIterations = 0;
};

// ----------------------------- Network -------------------------------------
static int HEED_N = 500;   // switch (ini: defines = "HEED_N=...")
static uint32_t N = HEED_N;   // ORIGINAL: paper's Fig. 8 uses 300-700 nodes (500 in Fig. 8d)
static constexpr double AREA = 100.0;
static constexpr double BSX = 50.0;
static constexpr double BSY = 175.0;  // ORIGINAL: paper's own Table 2, "Sink at (50,175)"
static constexpr double E0 = 2.0;       // J/node -- ORIGINAL: paper's Table 2, "Initial energy: 2 J/battery"
static constexpr double RANGE = 25.0;   // m

// ------------------------------- HEED --------------------------------------
// FIX 2: restored to the original published-style values.
static constexpr double CPROB = 0.05;   // ORIGINAL: paper's own example (Cprob=5%, Table 2 & Sec.4)
static constexpr double PMIN = 0.0005;  // ORIGINAL: paper's Section 4 default (pmin=0.0005)

// --------------------------- Radio / traffic -------------------------------
static constexpr uint32_t PACKET_BITS = 800 + 200; // ORIGINAL: Table 2, 100-byte data + 25-byte header
static constexpr uint32_t FRAMES_PER_ROUND = 5;   // ORIGINAL: Table 2, "Round (T_NO): 5 TDM frames"
static constexpr uint32_t CONTROL_BITS = 200;   // matches paper's Table 2, "Broadcast packet size: 25 bytes"
static constexpr double E_ELEC = 50e-9;       // J/bit
static constexpr double E_FS = 10e-12;         // J/bit/m^2
static constexpr double E_MP = 0.0013e-12;     // J/bit/m^4
static constexpr double E_DA = 5e-9;           // J/bit
static constexpr double DATA_RATE = 250000.0;  // bit/s
static constexpr double LIGHT = 3.0e8;         // m/s

static constexpr uint32_t MAX_ROUNDS = 20000; // run until the last node dies
static constexpr uint32_t SEED = 12345;

// ----------------------------- Geometry ------------------------------------
static double Dist(const SensorNode& a, const SensorNode& b)
{
    return hypot(a.x - b.x, a.y - b.y);
}

static double DistBS(const SensorNode& a)
{
    return hypot(a.x - BSX, a.y - BSY);
}

static double D0()
{
    return 75.0;  // ORIGINAL: paper's Table 2 states "Threshold distance (d0): 75 m" directly
                  // (differs slightly from sqrt(Efs/Emp) ~= 87.7m with these Efs/Emp values)
}

// --------------------------- Energy model ----------------------------------
static double TxEnergy(uint32_t bits, double d)
{
    if (d <= 0.0)
        return bits * E_ELEC;

    if (d < D0())
        return bits * (E_ELEC + E_FS * d * d);

    return bits * (E_ELEC + E_MP * pow(d, 4.0));
}

static double RxEnergy(uint32_t bits)
{
    return bits * E_ELEC;
}

static double AggEnergy(uint32_t bits)
{
    return bits * E_DA;
}

static double TxTimeSec(uint32_t bits)
{
    return static_cast<double>(bits) / DATA_RATE;
}

static double DelayMs(uint32_t bits, double d)
{
    return (TxTimeSec(bits) + d / LIGHT) * 1000.0;
}

// ---------------------------- Connectivity ---------------------------------
static vector<vector<uint32_t>> BuildNeighbors(const vector<SensorNode>& nodes)
{
    vector<vector<uint32_t>> nb(N);

    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive)
            continue;

        for (uint32_t j = 0; j < N; ++j) {
            if (i == j || !nodes[j].alive)
                continue;

            if (Dist(nodes[i], nodes[j]) <= RANGE)
                nb[i].push_back(j);
        }
    }

    return nb;
}

static void UpdateCost(vector<SensorNode>& nodes,
                       const vector<vector<uint32_t>>& nb)
{
    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive) {
            nodes[i].degree = 0;
            nodes[i].cost = numeric_limits<double>::infinity();
            continue;
        }

        nodes[i].degree = static_cast<uint32_t>(nb[i].size());

        // FIX 1: invert so higher degree (well-connected hub) => lower
        // cost => wins the local BestCH competition, instead of the
        // opposite (which favored isolated/low-degree nodes).
        nodes[i].cost = 1.0 / (static_cast<double>(nodes[i].degree) + 1.0);
    }
}

static uint32_t BestCH(const vector<uint32_t>& candidates,
                       const vector<SensorNode>& nodes)
{
    NS_ASSERT(!candidates.empty());

    uint32_t best = candidates.front();

    for (uint32_t c : candidates) {
        if (nodes[c].cost < nodes[best].cost ||
            (fabs(nodes[c].cost - nodes[best].cost) < 1e-12 && c < best)) {
            best = c;
        }
    }

    return best;
}

// ------------------------------ HEED ---------------------------------------
// Number of cluster_head_msg announcements each node sent in the last election
static vector<uint32_t> g_announce;

// HEED election -- the paper's pseudocode (Fig. 2), synchronous iterations
static uint32_t RunHEED(vector<SensorNode>& nodes,
                        const vector<vector<uint32_t>>& nb,
                        mt19937& rng)
{
    uniform_real_distribution<double> U(0.0, 1.0);
    g_announce.assign(N, 0);
    vector<bool> done(N, false);

    // Phase I: CH_prob = max(Cprob * Eresidual / Emax, pmin)
    for (auto& n : nodes) {
        n.tentative = false;
        n.finalCH = false;
        n.clusterHead = numeric_limits<uint32_t>::max();
        n.chProb = n.alive ? max(CPROB * n.energy / E0, PMIN) : 0.0;
        done[n.id] = !n.alive;
    }

    // Phase II: repeat ... until CH_previous = 1 (per node)
    uint32_t iterations = 0;
    while (iterations < 64) {
        bool anyRunning = false;
        for (uint32_t i = 0; i < N; ++i)
            if (!done[i]) anyRunning = true;
        if (!anyRunning)
            break;
        ++iterations;

        vector<bool> oldT(N), oldF(N);
        for (uint32_t i = 0; i < N; ++i) {
            oldT[i] = nodes[i].tentative;
            oldF[i] = nodes[i].finalCH;
        }
        vector<bool> newT = oldT, newF = oldF;

        for (uint32_t i = 0; i < N; ++i) {
            if (done[i])
                continue;

            // S_CH = {v : v is a (tentative or final) cluster head}
            vector<uint32_t> sch;
            for (uint32_t c : nb[i])
                if (nodes[c].alive && (oldT[c] || oldF[c]))
                    sch.push_back(c);
            if (oldT[i] || oldF[i])
                sch.push_back(i);

            newT[i] = false;
            if (!sch.empty()) {
                if (BestCH(sch, nodes) == i) {           // my_cluster_head = me
                    if (nodes[i].chProb >= 1.0 - 1e-12) newF[i] = true;   // final_CH msg
                    else                                newT[i] = true;   // tentative_CH msg
                    ++g_announce[i];
                }
            } else if (nodes[i].chProb >= 1.0 - 1e-12) {  // ElseIf CH_prob = 1
                newF[i] = true;
                ++g_announce[i];
            } else if (U(rng) <= nodes[i].chProb) {       // ElseIf Random <= CH_prob
                newT[i] = true;
                ++g_announce[i];
            }

            const double previous = nodes[i].chProb;
            nodes[i].chProb = min(2.0 * nodes[i].chProb, 1.0);
            if (previous >= 1.0 - 1e-12)
                done[i] = true;
        }

        for (uint32_t i = 0; i < N; ++i) {
            nodes[i].tentative = newT[i] && !newF[i];
            nodes[i].finalCH = newF[i];
        }
    }

    // Phase III: finalize
    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive || nodes[i].finalCH)
            continue;
        bool heardFinal = false;
        for (uint32_t c : nb[i])
            if (nodes[c].alive && nodes[c].finalCH) { heardFinal = true; break; }
        if (!heardFinal) {                  // uncovered -> announce final CH
            nodes[i].finalCH = true;
            ++g_announce[i];
        }
    }
    for (auto& n : nodes)
        n.tentative = false;

    // join_cluster: least-cost final CH within cluster range
    for (auto& n : nodes) {
        n.clusterHead = numeric_limits<uint32_t>::max();
        if (!n.alive)
            continue;
        if (n.finalCH) {
            n.clusterHead = n.id;
            continue;
        }
        vector<uint32_t> candidates;
        for (uint32_t c : nb[n.id])
            if (nodes[c].alive && nodes[c].finalCH)
                candidates.push_back(c);
        if (!candidates.empty())
            n.clusterHead = BestCH(candidates, nodes);
    }

    return iterations;
}

// ---------------------------- Round simulation -----------------------------
static RoundResult SimulateRound(vector<SensorNode>& nodes,
                                 uint32_t round,
                                 uint32_t heedIterations)
{
    RoundResult r;
    r.round = round;
    r.heedIterations = heedIterations;

    const double before = [&]() {
        double sum = 0.0;
        for (const auto& n : nodes)
            sum += n.energy;
        return sum;
    }();

    // ---- Control-message energy (paper Lemma 4) ----
    // A node dies when it cannot afford a message.
    auto spend = [&](uint32_t i, double e) -> bool {
        if (!nodes[i].alive) return false;
        if (e >= nodes[i].energy) { nodes[i].energy = 0.0; nodes[i].alive = false; return false; }
        nodes[i].energy -= e;
        return true;
    };
    auto startNb = BuildNeighbors(nodes);
    // Phase I: every node broadcasts its cost once; neighbours receive it.
    // Phase II/III: every cluster_head_msg announcement (tentative or final).
    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive)
            continue;
        const uint32_t msgs = 1 + g_announce[i];
        for (uint32_t m = 0; m < msgs; ++m) {
            if (!spend(i, TxEnergy(CONTROL_BITS, RANGE)))
                break;
            ++r.controlTx;
            for (uint32_t v : startNb[i])
                if (spend(v, RxEnergy(CONTROL_BITS)))
                    ++r.controlRx;
        }
    }
    // join_cluster: a regular node's single join message to its CH.
    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive || nodes[i].finalCH)
            continue;
        const uint32_t c = nodes[i].clusterHead;
        if (c >= N || !nodes[c].alive)
            continue;
        if (!spend(i, TxEnergy(CONTROL_BITS, Dist(nodes[i], nodes[c]))))
            continue;
        ++r.controlTx;
        if (spend(c, RxEnergy(CONTROL_BITS)))
            ++r.controlRx;
    }

    auto liveNb = BuildNeighbors(nodes);

    for (auto& n : nodes) {
        if (!n.alive)
            n.finalCH = false;
    }

    liveNb = BuildNeighbors(nodes);

    for (auto& n : nodes) {
        if (!n.alive) {
            n.clusterHead = numeric_limits<uint32_t>::max();
            continue;
        }

        if (n.finalCH) {
            n.clusterHead = n.id;
            continue;
        }

        vector<uint32_t> candidates;
        for (uint32_t c : liveNb[n.id]) {
            if (nodes[c].alive && nodes[c].finalCH)
                candidates.push_back(c);
        }

        n.clusterHead = candidates.empty()
            ? numeric_limits<uint32_t>::max()
            : BestCH(candidates, nodes);
    }

    for (const auto& n : nodes)
        if (n.alive && n.finalCH)
            ++r.chCount;

    // ---- Steady state: 5 TDM frames per round (paper Table 2) ----
    double delaySum = 0.0;
    uint32_t deliveredSources = 0;
    for (uint32_t frame = 0; frame < FRAMES_PER_ROUND; ++frame) {
    for (const auto& n : nodes)
        if (n.alive)
            ++r.generated;

        vector<uint32_t> membersPerCH(N, 0);
        vector<bool> memberDeliveredToCH(N, false);
        vector<double> delayToCH(N, 0.0);

        for (uint32_t i = 0; i < N; ++i) {
            if (!nodes[i].alive || nodes[i].finalCH)
                continue;

            uint32_t c = nodes[i].clusterHead;

            if (c >= N || !nodes[c].alive || !nodes[c].finalCH) {
                ++r.unclustered;
                continue;
            }

            double d = Dist(nodes[i], nodes[c]);
            if (d > RANGE) {
                ++r.unclustered;
                continue;
            }

            double tx = TxEnergy(PACKET_BITS, d);
            double rx = RxEnergy(PACKET_BITS);

            if (tx > nodes[i].energy || rx > nodes[c].energy) {
                ++r.lost;
                continue;
            }

            nodes[i].energy -= tx;
            nodes[c].energy -= rx;
            ++r.dataTx;
            ++r.dataRx;
            ++membersPerCH[c];
            memberDeliveredToCH[i] = true;
            delayToCH[i] = DelayMs(PACKET_BITS, d);
        }

        for (uint32_t c = 0; c < N; ++c) {
            if (!nodes[c].alive || !nodes[c].finalCH)
                continue;

            const uint32_t members = membersPerCH[c];
            const double agg = static_cast<double>(members + 1) * AggEnergy(PACKET_BITS); // members' + own signal

            if (agg > nodes[c].energy) {
                ++r.lost;
                nodes[c].energy = 0.0;
                nodes[c].alive = false;
                continue;
            }

            nodes[c].energy -= agg;

            const double dBS = DistBS(nodes[c]);
            const double txBS = TxEnergy(PACKET_BITS, dBS);

            if (txBS > nodes[c].energy) {
                ++r.lost;
                nodes[c].energy = 0.0;
                nodes[c].alive = false;
                continue;
            }

            nodes[c].energy -= txBS;
            ++r.dataTx;
            ++r.dataRx;

            deliveredSources += members + 1;
            delaySum += DelayMs(PACKET_BITS, dBS);

            for (uint32_t i = 0; i < N; ++i) {
                if (memberDeliveredToCH[i] && nodes[i].clusterHead == c)
                    delaySum += delayToCH[i] + DelayMs(PACKET_BITS, dBS);
            }
        }
    }

    r.delivered = min(deliveredSources, r.generated);
    r.lost = r.generated - r.delivered;

    double after = 0.0;
    uint32_t assigned = 0;

    for (auto& n : nodes) {
        if (n.energy <= 0.0) {
            n.energy = 0.0;
            n.alive = false;
        }

        after += n.energy;

        if (n.alive)
            ++r.alive;

        if (n.alive && !n.finalCH &&
            n.clusterHead < N &&
            nodes[n.clusterHead].alive &&
            nodes[n.clusterHead].finalCH) {
            ++assigned;
        }
    }

    r.dead = N - r.alive;
    r.energyUsed = max(0.0, before - after);
    r.residualEnergy = after;

    r.avgClusterSize = r.chCount
        ? static_cast<double>(assigned + r.chCount) / r.chCount
        : 0.0;

    if (r.alive == 0)
    {
        r.chCount = 0;
        r.generated = 0;
        r.delivered = 0;
        r.lost = 0;
        r.unclustered = 0;
        r.avgClusterSize = 0.0;
        r.avgDelayMs = 0.0;
        r.pdr = 0.0;
        r.throughputKbps = 0.0;
    }

    r.pdr = r.generated
        ? static_cast<double>(r.delivered) / r.generated
        : 0.0;

    r.avgDelayMs = r.delivered
        ? delaySum / r.delivered
        : 0.0;

    const double controlTime =
        static_cast<double>(r.controlTx) * TxTimeSec(CONTROL_BITS);
    const double dataTxTime =
        static_cast<double>(r.dataTx) * TxTimeSec(PACKET_BITS);
    r.roundDurationSec = controlTime + dataTxTime;

    r.throughputKbps = r.roundDurationSec > 0.0
        ? static_cast<double>(r.delivered * PACKET_BITS) /
          r.roundDurationSec / 1000.0
        : 0.0;

    return r;
}

// ------------------------------- Main --------------------------------------
static void InitSwitches(wsn::Hook& hook)
{
    HEED_N = static_cast<int>(hook.Define("HEED_N", 500));
    N = HEED_N;
}

static int Run(wsn::Hook& HOOK)
{
    InitSwitches(HOOK);
    HOOK.SetBaseStation(BSX, BSY);

    wsn::Out() << "\n========================================\n";
    wsn::Out() << "   ORIGINAL HEED (bug-fixed baseline)\n";
    wsn::Out() << "========================================\n";
    wsn::Out() << "Nodes = " << N << "\n";
    wsn::Out() << "Area = " << AREA << " x " << AREA << " m\n";
    wsn::Out() << "BS = (" << BSX << ", " << BSY << ")\n";
    wsn::Out() << "Initial Energy = " << E0 << " J/node\n";
    wsn::Out() << "Cprob = " << CPROB << " | pMin = " << PMIN << "\n";
    wsn::Out() << "Cost = 1/(degree+1)  [corrected to favor high-degree hub nodes]\n";
    wsn::Out() << "Range = " << RANGE << " m\n";
    wsn::Out() << "Packet = " << PACKET_BITS << " bits\n";
    wsn::Out() << "Radio d0 = " << D0() << " m\n";
    wsn::Out() << "Metrics = analytical baseline (not PHY/MAC packet-level)\n";
    wsn::Out() << "Visualization = OMNeT++ (Qtenv)\n";
    wsn::Out() << "========================================\n";

    mt19937 rng(SEED);
    uniform_real_distribution<double> pos(0.0, AREA);

    vector<SensorNode> nodes(N);

    for (uint32_t i = 0; i < N; ++i) {
        nodes[i].id = i;
        nodes[i].x = pos(rng);
        nodes[i].y = pos(rng);
        nodes[i].energy = E0;
        nodes[i].alive = true;
        nodes[i].tentative = false;
        nodes[i].finalCH = false;
        nodes[i].clusterHead = numeric_limits<uint32_t>::max();
        nodes[i].degree = 0;
        nodes[i].cost = 0.0;
        nodes[i].chProb = 0.0;
    }

    ofstream rounds(wsn::CsvPath("heed_ORIGINAL-results.csv"));
    ofstream energy(wsn::CsvPath("heed_ORIGINAL-node-energy.csv"));
    ofstream lifetime(wsn::CsvPath("heed_ORIGINAL-node-lifetime.csv"));

    if (!rounds || !energy || !lifetime)
        NS_FATAL_ERROR("Cannot create CSV output files.");

    rounds << "Round,Alive,Dead,CH_Count,Generated,Delivered,Lost,Unclustered,"
              "HEED_Iterations,Control_TX,Control_RX,Data_TX,Data_RX,"
              "Energy_Used_J,Residual_Energy_J,Avg_Cluster_Size,Avg_Delay_ms,"
              "PDR,Round_Duration_s,Throughput_kbps\n";

    energy << "Round,Node,Energy_J,Alive,Is_CH,ClusterHead\n";
    lifetime << "Node,Death_Round\n";

    uint32_t FND = 0;
    uint32_t HND = 0;
    uint32_t LND = 0;
    bool fnd = false;
    bool hnd = false;

    vector<uint32_t> deathRound(N, 0);

    uint64_t totalGenerated = 0;
    uint64_t totalDelivered = 0;
    double totalUsed = 0.0;

    wsn::Out() << "\nSimulation starts...\n";

    for (uint32_t round = 1; round <= MAX_ROUNDS; ++round) {
        auto nb = BuildNeighbors(nodes);
        UpdateCost(nodes, nb);

        uint32_t heedIterations = RunHEED(nodes, nb, rng);
        RoundResult r = SimulateRound(nodes, round, heedIterations);
        HOOK.Round(round, r, nodes);   // OMNeT++: one round = one step of simulation time

        totalGenerated += r.generated;
        totalDelivered += r.delivered;
        totalUsed += r.energyUsed;

        rounds << fixed << setprecision(10)
               << r.round << ','
               << r.alive << ','
               << r.dead << ','
               << r.chCount << ','
               << r.generated << ','
               << r.delivered << ','
               << r.lost << ','
               << r.unclustered << ','
               << r.heedIterations << ','
               << r.controlTx << ','
               << r.controlRx << ','
               << r.dataTx << ','
               << r.dataRx << ','
               << r.energyUsed << ','
               << r.residualEnergy << ','
               << r.avgClusterSize << ','
               << r.avgDelayMs << ','
               << r.pdr << ','
               << r.roundDurationSec << ','
               << r.throughputKbps << '\n';

        for (const auto& n : nodes) {
            energy << round << ','
                   << n.id << ','
                   << setprecision(10) << n.energy << ','
                   << (n.alive ? 1 : 0) << ','
                   << (n.alive && n.finalCH ? 1 : 0) << ','
                   << (n.clusterHead < N ? to_string(n.clusterHead) : "-1")
                   << '\n';

            if (!n.alive && deathRound[n.id] == 0)
                deathRound[n.id] = round;
        }

        if (!fnd && r.dead >= 1) {
            FND = round;
            fnd = true;
        }

        if (!hnd && r.alive <= N / 2) {
            HND = round;
            hnd = true;
        }

        wsn::Out() << fixed << setprecision(4)
             << "Round " << setw(4) << round
             << " | Alive=" << setw(3) << r.alive
             << " | CH=" << setw(3) << r.chCount
             << " | Generated=" << setw(3) << r.generated
             << " | Delivered=" << setw(3) << r.delivered
             << " | PDR=" << setw(7) << r.pdr
             << " | Residual=" << setw(9) << r.residualEnergy << " J\n";

        if (r.alive == 0) {
            LND = round;
            break;
        }
    }

    // LND is only reported when the last node really died (otherwise "Not reached").

    for (uint32_t i = 0; i < N; ++i) {
        lifetime << i << ','
                 << (deathRound[i] ? to_string(deathRound[i]) : "Not_Dead")
                 << '\n';
    }

    rounds.close();
    energy.close();
    lifetime.close();

    const double overallPdr = totalGenerated
        ? static_cast<double>(totalDelivered) / totalGenerated
        : 0.0;

    wsn::Out() << "\n========================================\n";
    wsn::Out() << "             FINAL RESULTS\n";
    wsn::Out() << "========================================\n";
    wsn::Out() << "FND = " << (fnd ? to_string(FND) : "Not reached") << " rounds\n";
    wsn::Out() << "HND = " << (hnd ? to_string(HND) : "Not reached") << " rounds\n";
    wsn::Out() << "LND = " << (LND ? to_string(LND) : "Not reached") << " rounds\n";
    wsn::Out() << fixed << setprecision(6);
    wsn::Out() << "Initial Network Energy = " << N * E0 << " J\n";
    wsn::Out() << "Total Energy Used      = " << totalUsed << " J\n";
    wsn::Out() << "Final Residual Energy  = " << max(0.0, N * E0 - totalUsed) << " J\n";
    wsn::Out() << "Generated Packets      = " << totalGenerated << "\n";
    wsn::Out() << "Delivered Packets      = " << totalDelivered << "\n";
    wsn::Out() << "Overall PDR            = " << overallPdr << "\n";
    wsn::Out() << "\nCSV outputs:\n";
    wsn::Out() << "  heed_ORIGINAL-results.csv\n";
    wsn::Out() << "  heed_ORIGINAL-node-energy.csv\n";
    wsn::Out() << "  heed_ORIGINAL-node-lifetime.csv\n";
    wsn::Out() << "========================================\n";

    {   // OMNeT++: final metrics, exactly as computed above
        wsn::FinalView fv;
        fv.FND = fnd ? FND : 0; fv.HND = hnd ? HND : 0; fv.LND = LND;
        fv.pdr = overallPdr; fv.energyUsed = totalUsed;
        fv.generated = totalGenerated; fv.delivered = totalDelivered;
        HOOK.Finish(fv);
    }
    return 0;
}


} // namespace wsn_heed_ORIGINAL

static wsn::Registrar wsn_heed_ORIGINAL_registrar("heed_ORIGINAL", "code/1_ORIGINAL/heed_ORIGINAL.cc", &wsn_heed_ORIGINAL::Run, {"HEED_N"});
