// OMNeT++ port of code/1_ORIGINAL/hleach_ORIGINAL.cc (thesis ns-3 program).
// Generated by omnetpp/tools/port_ns3.py: the protocol logic below is the
// original code, unchanged; see the header of that script for what was adapted.

#include "WsnRuntime.h"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <random>
#include <string>
#include <vector>

using namespace std;

namespace wsn_hleach_ORIGINAL {
// ============================================================================
// H-LEACH -- ORIGINAL (paper-faithful reproduction)
// ns-3.41 / C++
//
// Razaque, Mudigulam, Gavini, Amsaad, Abdulgader & Krishna (2016)
// "H-LEACH: Hybrid-Low Energy Adaptive Clustering Hierarchy for WSNs"
// 2016 IEEE Long Island Systems, Applications and Technology Conf. (LISAT)
//
// ALGORITHM (from the paper's own Algorithm 1 pseudocode):
//   For each alive node i, each round r:
//     e0(i) = P * (Eresidual_i / Emax)          -- an energy-weighted
//                                                   "probability" (same
//                                                   structure as HEED's
//                                                   CHprob formula)
//     epoch = round(1 / e0(i))
//     t(n)  = e0(i) / (1 - e0(i) * (r mod epoch))  -- LEACH's own threshold
//                                                     formula, but using
//                                                     the per-node,
//                                                     energy-weighted e0(i)
//                                                     in place of LEACH's
//                                                     constant P
//     node becomes CH this round IF: random(0,1) < t(n)  AND
//                                     energy_i > average energy of all
//                                     currently-alive nodes
//   Members join the nearest CH (paper does not specify a join rule
//   explicitly; nearest-CH is the standard simplification used throughout
//   this thesis for every reproduced protocol).
//
// CRITICAL RECONSTRUCTION FINDING (please read before using this file):
//   The paper's own pseudocode, AS WRITTEN, has no fallback for what
//   happens if NO node satisfies both the threshold draw AND the
//   "energy > average" condition in a given round. A direct Python
//   verification of this exact formula found that, under the paper's own
//   Table 1 parameters, EVERY SINGLE ROUND fails to produce a single
//   qualifying candidate -- i.e., the algorithm as literally described
//   never selects a cluster head at all, and no node would ever transmit
//   or die. This is obviously inconsistent with the paper's own reported
//   result (last node dying at round ~4312), so their actual
//   implementation must have included some unstated fallback.
//   This file adds the same fallback used throughout this thesis for
//   every other protocol (LEACH, HEED, SH-LEACH, EECH-HEED): if no node
//   qualifies, the single highest-energy alive node is forced to become
//   CH. This is a disclosed, necessary assumption, not a deviation from
//   the paper's intent.
//
// PARAMETERS (Table 1 + the paper's second parameter table):
//   N=100, 100x100m field, Sink at center (50,50) [paper: 0.5*Xm, 0.5*Ym],
//   Eelec=50nJ/bit, Efs=10pJ/bit/m^2, Emp=0.0013pJ/bit/m^4 [the paper's
//   OCR'd second table gives both Efs and Emp separately, confirming a
//   two-slope model was actually used, despite Table 1 separately -- and
//   inconsistently -- listing a single "Eamp=100pJ" value; the two-slope
//   values are used here as the more specific and internally consistent
//   of the paper's own two conflicting statements], E_DA=5nJ/bit,
//   P=0.1, E0=0.5J, packet=4000 bits (paper's "Kbit"), 5000 max rounds
//   (paper states "Max Interval=4000" in Table 1, but its own results
//   section reports H-LEACH's last node dying at round 4312 -- an
//   internal inconsistency in the paper itself; 5000 is used here so the
//   simulation can actually reach whatever round the dynamics produce).
//
// PAPER-FIDELITY FIXES (this revision):
//   - E_avg = (sum of e_n) / n with n = ALL nodes (Algorithm 1, line 4),
//     dead nodes counting as 0 J -- not the average over alive nodes only.
//   - Fusion: members' signals + the CH's own (E_DA per signal).
//   - A node with no CH transmits directly to the BS.
//   - Runs until the last node dies (LND never taken from a capped run).
//   - The paper's per-round constant E_tr has no stated value, so energy
//     is computed with the paper's own radio constants (Eelec/Efs/Emp/E_DA).
//   - The paper mentions a "second channel head" but its Algorithm 1 never
//     defines one, so none is implemented.
//   - The paper describes no setup/control messages; none are charged here.
//     (The unified EDITED/IMPROVED files charge LEACH-style setup messages,
//     like every protocol in the unified environment.)
// For the version made directly comparable with LEACH/HEED/etc. under
// this thesis's unified environment, see hleach_EDITED_unified.cc.
// ============================================================================

struct SensorNode {
    uint32_t id = 0;
    double x = 0.0;
    double y = 0.0;
    double energy = 0.0;
    bool alive = true;
    bool finalCH = false;
    uint32_t clusterHead = numeric_limits<uint32_t>::max();
};

struct RoundResult {
    uint32_t round = 0;
    uint32_t alive = 0;
    uint32_t dead = 0;
    uint32_t chCount = 0;
    uint32_t generated = 0;
    uint32_t delivered = 0;
    uint32_t lost = 0;
    uint32_t fallbackUsed = 0; // NEW: 1 if the "no qualifying candidate" fallback fired this round
    uint64_t dataTx = 0;
    uint64_t dataRx = 0;
    double energyUsed = 0.0;
    double residualEnergy = 0.0;
    double avgDelayMs = 0.0;
    double pdr = 0.0;
    double throughputKbps = 0.0;
    double roundDurationSec = 0.0;
};

// ----------------------------- Network -------------------------------------
static constexpr uint32_t N = 100;
static constexpr double AREA = 100.0;
static constexpr double BSX = 50.0;
static constexpr double BSY = 50.0;
static constexpr double E0 = 0.5;

// ------------------------------- Protocol params ----------------------------
static constexpr double P_CH = 0.1;             // paper's "Probability to become CH"
static constexpr double GATE_FACTOR = 1.0;      // ORIGINAL: strict "energy > average" gate (paper's literal condition)

// --------------------------- Radio / traffic -------------------------------
static constexpr uint32_t PACKET_BITS = 4000;   // paper's "Kbit"
static constexpr double E_ELEC = 50e-9;
static constexpr double E_FS = 10e-12;
static constexpr double E_MP = 0.0013e-12;
static constexpr double E_DA = 5e-9;
static constexpr double DATA_RATE = 250000.0;
static constexpr double LIGHT = 3.0e8;

static constexpr uint32_t MAX_ROUNDS = 20000; // run until the last node dies
static constexpr bool COUNT_SETUP_ENERGY = false;   // paper describes no control messages
static constexpr uint32_t CONTROL_BITS = 200;
static const double ADV_RANGE = AREA * std::sqrt(2.0);
static constexpr uint32_t SEED = 12345;

// ----------------------------- Geometry ------------------------------------
static double Dist(const SensorNode& a, const SensorNode& b) { return hypot(a.x - b.x, a.y - b.y); }
static double DistBS(const SensorNode& a) { return hypot(a.x - BSX, a.y - BSY); }
static double D0() { return sqrt(E_FS / E_MP); }

static double TxEnergy(uint32_t bits, double d)
{
    if (d <= 0.0) return bits * E_ELEC;
    if (d < D0()) return bits * (E_ELEC + E_FS * d * d);
    return bits * (E_ELEC + E_MP * pow(d, 4.0));
}
static double RxEnergy(uint32_t bits) { return bits * E_ELEC; }
static double AggEnergy(uint32_t bits) { return bits * E_DA; }
static double TxTimeSec(uint32_t bits) { return static_cast<double>(bits) / DATA_RATE; }
static double DelayMs(uint32_t bits, double d) { return (TxTimeSec(bits) + d / LIGHT) * 1000.0; }

// --------------------- H-LEACH selection (paper's Algorithm 1) -------------
static uint32_t RunSelection(vector<SensorNode>& nodes, uint32_t round, mt19937& rng, uint32_t& fallbackFired)
{
    uniform_real_distribution<double> U(0.0, 1.0);

    for (auto& n : nodes) { n.finalCH = false; n.clusterHead = numeric_limits<uint32_t>::max(); }

    double sumEnergy = 0.0;
    uint32_t aliveCount = 0;
    for (const auto& n : nodes) if (n.alive) { sumEnergy += n.energy; ++aliveCount; }
    (void)aliveCount;
    const double eAvg = sumEnergy / static_cast<double>(N);   // Algorithm 1 line 4: sum(e_n) / n, n = all nodes

    vector<uint32_t> candidates;
    for (auto& n : nodes) {
        if (!n.alive) continue;
        const double e0i = P_CH * (n.energy / E0);
        if (e0i <= 0.0) continue;
        const uint32_t epoch = max<uint32_t>(1, static_cast<uint32_t>(lround(1.0 / e0i)));
        const double denom = 1.0 - e0i * static_cast<double>(round % epoch);
        double tn = (denom > 1e-9) ? (e0i / denom) : 1.0;
        tn = min(1.0, max(0.0, tn));

        if (U(rng) < tn && n.energy > GATE_FACTOR * eAvg) {
            candidates.push_back(n.id);
        }
    }

    fallbackFired = 0;
    if (candidates.empty()) {
        // See header note: necessary, disclosed fallback -- the paper's own
        // pseudocode never selects a CH without this under its own parameters.
        fallbackFired = 1;
        uint32_t best = numeric_limits<uint32_t>::max();
        double bestEnergy = -1.0;
        for (const auto& n : nodes) {
            if (n.alive && n.energy > bestEnergy) { bestEnergy = n.energy; best = n.id; }
        }
        if (best != numeric_limits<uint32_t>::max()) candidates.push_back(best);
    }

    for (uint32_t id : candidates) nodes[id].finalCH = true;

    uint32_t chCount = 0;
    for (const auto& n : nodes) if (n.alive && n.finalCH) ++chCount;

    // ---- Nearest-CH join (paper does not specify a join rule) ----
    for (auto& n : nodes) {
        n.clusterHead = numeric_limits<uint32_t>::max();
        if (!n.alive) continue;
        if (n.finalCH) { n.clusterHead = n.id; continue; }

        double bestDistance = numeric_limits<double>::infinity();
        uint32_t bestCH = numeric_limits<uint32_t>::max();
        for (const auto& c : nodes) {
            if (!c.alive || !c.finalCH) continue;
            const double d = Dist(n, c);
            if (d < bestDistance - 1e-12 || (fabs(d - bestDistance) < 1e-12 && c.id < bestCH)) {
                bestDistance = d;
                bestCH = c.id;
            }
        }
        if (bestCH != numeric_limits<uint32_t>::max()) n.clusterHead = bestCH;
    }

    return chCount;
}

// ---------------------------- Round simulation -----------------------------
static RoundResult SimulateRound(vector<SensorNode>& nodes, uint32_t round, mt19937& rng)
{
    RoundResult r;
    r.round = round;

    const double before = [&]() { double s = 0.0; for (const auto& n : nodes) s += n.energy; return s; }();

    uint32_t fallbackFired = 0;
    RunSelection(nodes, round, rng, fallbackFired);
    r.fallbackUsed = fallbackFired;

    // ---- Setup control messages (LEACH-style) -- only in the unified files ----
    if (COUNT_SETUP_ENERGY) {
        auto spend = [&](uint32_t i, double e) -> bool {
            if (!nodes[i].alive) return false;
            if (e > nodes[i].energy) { nodes[i].energy = 0.0; nodes[i].alive = false; nodes[i].finalCH = false; return false; }
            nodes[i].energy -= e; return true;
        };
        for (uint32_t c = 0; c < N; ++c) {                       // CH advertisement, heard by all
            if (!nodes[c].alive || !nodes[c].finalCH) continue;
            if (!spend(c, TxEnergy(CONTROL_BITS, ADV_RANGE))) continue;
            for (uint32_t v = 0; v < N; ++v) if (v != c) spend(v, RxEnergy(CONTROL_BITS));
        }
        for (uint32_t i = 0; i < N; ++i) {                       // join request
            if (!nodes[i].alive || nodes[i].finalCH) continue;
            const uint32_t c = nodes[i].clusterHead;
            if (c >= N || !nodes[c].alive) continue;
            if (spend(i, TxEnergy(CONTROL_BITS, Dist(nodes[i], nodes[c])))) spend(c, RxEnergy(CONTROL_BITS));
        }
        for (uint32_t c = 0; c < N; ++c) {                       // TDMA schedule to the farthest member
            if (!nodes[c].alive || !nodes[c].finalCH) continue;
            double far = 0.0; bool any = false;
            for (uint32_t i = 0; i < N; ++i)
                if (nodes[i].alive && !nodes[i].finalCH && nodes[i].clusterHead == c) { any = true; far = max(far, Dist(nodes[i], nodes[c])); }
            if (!any || !spend(c, TxEnergy(CONTROL_BITS, far))) continue;
            for (uint32_t i = 0; i < N; ++i)
                if (nodes[i].alive && !nodes[i].finalCH && nodes[i].clusterHead == c) spend(i, RxEnergy(CONTROL_BITS));
        }
    }

    for (const auto& n : nodes) if (n.alive && n.finalCH) ++r.chCount;
    for (const auto& n : nodes) if (n.alive) ++r.generated;
    uint32_t directDelivered = 0;
    double directDelaySum = 0.0;

    vector<uint32_t> membersPerCH(N, 0);
    vector<bool> memberDelivered(N, false);
    vector<double> delayToCH(N, 0.0);

    for (uint32_t i = 0; i < N; ++i) {
        if (!nodes[i].alive || nodes[i].finalCH) continue;
        const uint32_t c = nodes[i].clusterHead;
        if (c >= N || !nodes[c].alive || !nodes[c].finalCH) {
            // no CH: transmit directly to the BS
            const double dBS = DistBS(nodes[i]);
            const double txBS = TxEnergy(PACKET_BITS, dBS);
            if (txBS > nodes[i].energy) { nodes[i].energy = 0.0; nodes[i].alive = false; continue; }
            nodes[i].energy -= txBS;
            ++r.dataTx; ++r.dataRx; ++directDelivered;
            directDelaySum += DelayMs(PACKET_BITS, dBS);
            continue;
        }
        const double d = Dist(nodes[i], nodes[c]);
        const double tx = TxEnergy(PACKET_BITS, d);
        const double rx = RxEnergy(PACKET_BITS);
        if (tx > nodes[i].energy || rx > nodes[c].energy) continue;
        nodes[i].energy -= tx;
        nodes[c].energy -= rx;
        ++r.dataTx; ++r.dataRx;
        ++membersPerCH[c];
        memberDelivered[i] = true;
        delayToCH[i] = DelayMs(PACKET_BITS, d);
    }

    double delaySum = 0.0;
    uint32_t deliveredSources = 0;

    for (uint32_t c = 0; c < N; ++c) {
        if (!nodes[c].alive || !nodes[c].finalCH) continue;
        const uint32_t members = membersPerCH[c];
        const double agg = static_cast<double>(members + 1) * AggEnergy(PACKET_BITS); // members' + own signal
        if (agg > nodes[c].energy) { nodes[c].energy = 0.0; nodes[c].alive = false; nodes[c].finalCH = false; continue; }
        nodes[c].energy -= agg;
        const double dBS = DistBS(nodes[c]);
        const double txBS = TxEnergy(PACKET_BITS, dBS);
        if (txBS > nodes[c].energy) { nodes[c].energy = 0.0; nodes[c].alive = false; nodes[c].finalCH = false; continue; }
        nodes[c].energy -= txBS;
        ++r.dataTx; ++r.dataRx;
        deliveredSources += members + 1;
        delaySum += DelayMs(PACKET_BITS, dBS);
        for (uint32_t i = 0; i < N; ++i)
            if (memberDelivered[i] && nodes[i].clusterHead == c)
                delaySum += delayToCH[i] + DelayMs(PACKET_BITS, dBS);
    }

    deliveredSources += directDelivered;
    delaySum += directDelaySum;
    r.delivered = min(deliveredSources, r.generated);
    r.lost = r.generated - r.delivered;

    double after = 0.0;
    r.alive = 0;
    for (auto& n : nodes) {
        if (n.energy <= 0.0) { n.energy = 0.0; n.alive = false; n.finalCH = false; }
        after += n.energy;
        if (n.alive) ++r.alive;
    }
    r.dead = N - r.alive;
    r.energyUsed = max(0.0, before - after);
    r.residualEnergy = after;
    r.pdr = r.generated ? static_cast<double>(r.delivered) / r.generated : 0.0;
    r.avgDelayMs = r.delivered ? delaySum / r.delivered : 0.0;

    const double dataTxTime = static_cast<double>(r.dataTx) * TxTimeSec(PACKET_BITS);
    r.roundDurationSec = dataTxTime;
    r.throughputKbps = r.roundDurationSec > 0.0
        ? static_cast<double>(r.delivered * PACKET_BITS) / r.roundDurationSec / 1000.0 : 0.0;

    return r;
}

static void InitSwitches(wsn::Hook& hook)
{
}

static int Run(wsn::Hook& HOOK)
{
    InitSwitches(HOOK);
    HOOK.SetBaseStation(BSX, BSY);

    wsn::Out() << "\n========================================\n";
    wsn::Out() << "  H-LEACH -- ORIGINAL (Razaque et al., 2016)\n";
    wsn::Out() << "========================================\n";
    wsn::Out() << "Nodes = " << N << " | Area = " << AREA << "x" << AREA << " m | BS = (" << BSX << "," << BSY << ")\n";
    wsn::Out() << "P = " << P_CH << " | E0 = " << E0 << " J | Gate factor = " << GATE_FACTOR << " (paper's literal \"energy>average\")\n";
    wsn::Out() << "NOTE: fallback CH selection is ACTIVE whenever no node satisfies both\n";
    wsn::Out() << "      conditions -- required for this algorithm to function at all (see file header).\n";
    wsn::Out() << "========================================\n";

    mt19937 topologyRng(SEED);
    mt19937 electionRng(SEED + 1);
    uniform_real_distribution<double> pos(0.0, AREA);
    vector<SensorNode> nodes(N);

    for (uint32_t i = 0; i < N; ++i) {
        nodes[i].id = i;
        nodes[i].x = pos(topologyRng);
        nodes[i].y = pos(topologyRng);
        nodes[i].energy = E0;
        nodes[i].alive = true;
    }

    ofstream positions(wsn::CsvPath("node-positions.csv"));
    positions << "Node,X,Y\n";
    for (const auto& n : nodes) positions << n.id << ',' << n.x << ',' << n.y << '\n';
    positions << N << ',' << BSX << ',' << BSY << '\n';
    positions.close();

    ofstream rounds(wsn::CsvPath("hleach_ORIGINAL-results.csv"));
    ofstream energy(wsn::CsvPath("hleach_ORIGINAL-node-energy.csv"));
    ofstream lifetime(wsn::CsvPath("hleach_ORIGINAL-node-lifetime.csv"));
    if (!rounds || !energy || !lifetime) NS_FATAL_ERROR("Cannot create CSV output files.");

    rounds << "Round,Alive,Dead,CH_Count,FallbackUsed,Generated,Delivered,Lost,"
              "Data_TX,Data_RX,Energy_Used_J,Residual_Energy_J,Avg_Delay_ms,"
              "PDR,Round_Duration_s,Throughput_kbps\n";
    energy << "Round,Node,Energy_J,Alive,Is_CH,ClusterHead\n";
    lifetime << "Node,Death_Round\n";

    uint32_t FND = 0, HND = 0, LND = 0;
    bool fnd = false, hnd = false;
    vector<uint32_t> deathRound(N, 0);
    uint64_t totalGenerated = 0, totalDelivered = 0, totalFallbacks = 0;
    double totalUsed = 0.0;

    wsn::Out() << "\nSimulation starts...\n";

    for (uint32_t round = 1; round <= MAX_ROUNDS; ++round) {
        RoundResult r = SimulateRound(nodes, round, electionRng);
        HOOK.Round(round, r, nodes);   // OMNeT++: one round = one step of simulation time

        totalGenerated += r.generated;
        totalDelivered += r.delivered;
        totalUsed += r.energyUsed;
        totalFallbacks += r.fallbackUsed;

        rounds << fixed << setprecision(10)
               << r.round << ',' << r.alive << ',' << r.dead << ',' << r.chCount << ',' << r.fallbackUsed << ','
               << r.generated << ',' << r.delivered << ',' << r.lost << ','
               << r.dataTx << ',' << r.dataRx << ',' << r.energyUsed << ',' << r.residualEnergy << ','
               << r.avgDelayMs << ',' << r.pdr << ',' << r.roundDurationSec << ',' << r.throughputKbps << '\n';

        for (const auto& n : nodes) {
            energy << round << ',' << n.id << ',' << setprecision(10) << n.energy << ','
                   << (n.alive ? 1 : 0) << ',' << (n.alive && n.finalCH ? 1 : 0) << ','
                   << (n.clusterHead < N ? to_string(n.clusterHead) : "-1") << '\n';
            if (!n.alive && deathRound[n.id] == 0) deathRound[n.id] = round;
        }

        if (!fnd && r.dead >= 1) { FND = round; fnd = true; }
        if (!hnd && r.alive <= N / 2) { HND = round; hnd = true; }

        wsn::Out() << fixed << setprecision(4)
             << "Round " << setw(4) << round << " | Alive=" << setw(3) << r.alive
             << " | CH=" << setw(3) << r.chCount << (r.fallbackUsed ? "*" : " ")
             << " | PDR=" << setw(7) << r.pdr << " | Residual=" << setw(9) << r.residualEnergy << " J\n";

        if (r.alive == 0) { LND = round; break; }
    }

    // LND is only reported when the last node really died.

    for (uint32_t i = 0; i < N; ++i)
        lifetime << i << ',' << (deathRound[i] ? to_string(deathRound[i]) : "Not_Dead") << '\n';

    rounds.close(); energy.close(); lifetime.close();

    const double overallPdr = totalGenerated ? static_cast<double>(totalDelivered) / totalGenerated : 0.0;

    wsn::Out() << "\n========================================\n";
    wsn::Out() << "             FINAL RESULTS\n";
    wsn::Out() << "========================================\n";
    wsn::Out() << "FND = " << (fnd ? to_string(FND) : "Not reached") << " rounds\n";
    wsn::Out() << "HND = " << (hnd ? to_string(HND) : "Not reached") << " rounds\n";
    wsn::Out() << "LND = " << (LND ? to_string(LND) : "Not reached") << " rounds\n";
    wsn::Out() << fixed << setprecision(6);
    wsn::Out() << "Total Energy Used = " << totalUsed << " J\n";
    wsn::Out() << "Overall PDR = " << overallPdr << "\n";
    wsn::Out() << "Rounds where fallback CH selection fired = " << totalFallbacks << "\n";
    wsn::Out() << "\nCSV outputs: hleach_ORIGINAL-results.csv, hleach_ORIGINAL-node-energy.csv,\n";
    wsn::Out() << "             hleach_ORIGINAL-node-lifetime.csv\n";
    wsn::Out() << "========================================\n";

    {   // OMNeT++: final metrics, exactly as computed above
        wsn::FinalView fv;
        fv.FND = fnd ? FND : 0; fv.HND = hnd ? HND : 0; fv.LND = LND;
        fv.pdr = overallPdr; fv.energyUsed = totalUsed;
        fv.generated = totalGenerated; fv.delivered = totalDelivered;
        HOOK.Finish(fv);
        HOOK.Scalar("totalFallbacks", static_cast<double>(totalFallbacks));
    }
    return 0;
}


} // namespace wsn_hleach_ORIGINAL

static wsn::Registrar wsn_hleach_ORIGINAL_registrar("hleach_ORIGINAL", "code/1_ORIGINAL/hleach_ORIGINAL.cc", &wsn_hleach_ORIGINAL::Run, {});
